var translated = translated || {};

translated.fr = {
	state :  {
		common : {
			"Ok" : "Ok",
			"Yes" : "Oui",
			"No" : "Non",
			"Back" : "Retour",
			"Next" : "Suivant",
			"None" : "Aucune",
			"Exit" : "Quitter",
			"Edit" : "Éditer",
			"Save" : "Enregistrer",
			"Add" : "Ajouter",
			"Done" : "Ok",
			"Close" : "Fermer",
			"Remove" : "Retirer",
			"Reload" : "Actualiser",
			"ReloadToUpdate" : "Actualiser pour mettre à jour",
			"Reset" : "Réinitialiser",
			"Delete" : "Supprimer",
			"Hide" : "Cacher",
			"Show" : "Afficher",
			"Days" : "Jours",
			"Keep" : "Conserver",
			"Select" : "Sélectionner",
			"Note" : "Avis",
			"Shortcuts" : "Raccourcis",
			"LearnShortcuts" : "Apprendre les raccourcis",
			"RightClick" : "Clic droit",
			"AnyElement" : "sur n'importe quel élément",
			"DoubleClick" : "Double-clic",
			"CommandClick" : "Commande + Clic droit ",
			"ControlClick" : "Ctrl + Clic droit ",
			"ShiftClick" : "Shift + Clic droit",
			"AltClick" : "Alt + Clic droit",
			"ESC" : "ESC (sur le clavier)",
			"OpenContextMenu" : "Ouvre le menu contextuel.",
			"OpenTheEditor" : "Ouvre l'éditeur",
			"OpenColorsAndFonts" : "Ouvre les couleurs et les polices (ou les styles d'image)",
			"OpensSizeAndPosition" : "Ouvre la taille et les positions",
			"ClosesTheDialog" : "Ferme la boîte de dialogue",
			"RemoveSelectedItems" : "Supprimer les éléments sélectionnés",
			"DeleteSelectedItems" : "Supprimer les objets sélectionnés",
			"DeleteConf" : "Êtes-vous sûr de vouloir supprimer cet élément ?",
			"DeleteManyConf" : "Êtes-vous sûr de vouloir supprimer les éléments sélectionnés?",
			"RemoveConf" : "Êtes-vous sûr de vouloir retirer cet élément ?",
			"RemoveManyConf" : "Êtes-vous sûr de vouloir supprimer les articles sélectionnés ?",
			"PCE" : "PCE",
			"Change" : "Changer",
			"Toggle" : "Basculer",
			"Why" : "Pourquoi",
			"What" : "Objet",
			"Example" : "Exemple",
			"ReadMore" : "Lire la suite",
			"Duplicate" : "Dupliquer",
			"UnPublish" : "Annuler la publication",
			"Search" : "Rechercher",
			"AddImage" : "Ajouter une image",
			"AddImageOrVideo" : "Ajouter une image ou une vidéo",
			"ChangeImage" : "Modifier l’image",
			"Title" : "Titre",
			"Password" : "Mot de passe",
			"Subtitle" : "Sous-titre",
			"Price" : "Prix",
			"Description" : "Description",
			"Template" : "Modèle",
			"Weight" : "Poids",
			"Text" : "Texte",
			"Name" : "Nom",
			"Address" : "Adresse",
			"Contacts" : "Contacts",
			"Country" : "Pays",
			"State" : "État",
			"Email" : "E-mail",
			"Phone" : "Téléphone",
			"Pages" : "Pages",
			"Products" : "Produits",
			"Posts" : "Posts",
			"Free" : "Free",
			"Light" : "Light",
			"Pro" : "Pro",
			"OrganizationId" : "Identifiant de l'organisation",
			"Comment" : "Commentaire",
			"Left" : "Gauche",
			"Center" : "Centre",
			"Right" : "Droite",
			"Top" : "Haut",
			"Bottom" : "Bas",
			"Justify" : "Justifié",
			"Fixed" : "Fixe",
			"Scroll" : "Défilement",
			"Repeat" : "Répéter",
			"NoRepeat" : "Ne pas répéter",
			"Cover" : "Couvrir",
			"Contain" : "Contenir",
			"OriginalSize" : "Taille originale",
			"StyleTheText" : "Mettre en forme le texte",
			"StyleEntireText" : "Mettre en forme le texte entier",
			"StyleSelectedWords" : "Mettre en forme la selection",
			"SelectWordsToStyle" : "Sélectionnez les mots à mettre en forme",
			"CantBeChangedInFf" : "Ne peut pas être modifié dans FireFox (à cause d'un bug dans le navigateur). Veuillez utiliser Chrome ou Safari.",
			"Icon" : "Icône",
			"Level" : "Niveau",
			"Item" : "Article",
			"Items" : "Objets",
			"Image" : "Image",
			"ImageOrVideo" : "Image ou vidéo",
			"Images" : "Images",
			"AddImages" : "Ajouter des images",
			"AddImagesOrVideos" : "Ajouter des images ou des vidéos",
			"MuteVideo" : "Couper le son de la Vidéo",
			"CoverVideo" : "Vidéo de couverture",
			"Sound" : "Son",
			"Mute" : "Muet",
			"AutoPlay" : "Lecture auto",
			"HideControls" : "Cacher les contrôles",
			"PlayInThumb" : "Lire la vidéo dans la miniature",
			"WillReplaceLink" : "Empêchera l'ouverture du lien",
			"Only" : "Seulement",
			"Url" : "Url",
			"ChangeUrl" : "Changer l’URL",
			"ChangeUrlConf" : "Si vous modifiez l'URL, vous devrez modifier tous les liens vers la page. Souhaitez-vous modifier l'URL?",
			"Date" : "Date",
			"Tags" : "Tags",
			"Overall" : "Général",
			"Header" : "Titre",
			"Headers" : "Titres",
			"Paragraphs" : "Paragraphes",
			"Logo" : "Logo",
			"Button" : "Bouton",
			"Border" : "Bordure",
			"Column" : "Colonne",
			"Columns" : "Colonnes",
			"Form" : "Formulaire",
			"Type" : "Type",
			"Message" : "Message",
			"OneLineText" : "Texte d'une ligne",
			"Option" : "Option",
			"Options" : "Options",
			"SocialMedia" : "Réseaux sociaux",
			"Link" : "Lien",
			"Links" : "Liens",
			"LinkTo" : "Lier à",
			"Slideshow" : "Diaporama",
			"Skills" : "Compétences",
			"Animations" : "Animations",
			"CaptionStyles" : "Styles de légende",
			"CaptionTitles" : "Titres de légende",
			"TitleStyles" : "Styles de titre",
			"SubtitlesStyles" : "Styles de sous-titres",
			"CaptionSubtitles" : "Sous-titres des légendes",
			"Buttons" : "Boutons",
			"ResetDefaultStyles" : "Réinitialiser les styles par défaut",
			"ColorAndFonts" : "Couleur et polices",
			"ImageStyles" : "Style d'image",
			"BackgroundAndBorders" : "Arrière plan et bordures",
			"BackgroundColor" : "Couleur d’arrière plan",
			"BackgroundImage" : "Image d’arrière plan",
			"BackgroundImagePosition" : "Position de l’image d’arrière-plan",
			"BackgroundImageScaling" : "Mise à l'échelle de l'image d'arrière-plan",
			"BarBackgroundColor" : "Barre – Couleur d'arrière-plan",
			"BarColor" : "Couleur de la barre",
			"TextColor" : "Couleur du texte",
			"Font" : "Police",
			"Fonts" : "Polices",
			"All" : "Tout",
			"SansSerif" : "Sans Serif",
			"Serif" : "Serif",
			"Display" : "Afficher",
			"Monospace" : "Monospace",
			"Normal" : "Normal",
			"Italic" : "Italique",
			"Oblique" : "Oblique",
			"FontSize" : "Taille de police",
			"FontWeight" : "Graisse de Police",
			"Bold" : "Gras",
			"Bolder" : "Plus gras",
			"Lighter" : "Plus fin",
			"FontStyle" : "Style de police",
			"TextDecoration" : "Décoration du texte",
			"TextAlign" : "Alignement du texte",
			"Underline" : "Souligner",
			"Overline" : "Surligner",
			"LineThrough" : "Barré",
			"LineHeight" : "Interligne",
			"LetterSpacing" : "Interlettrage",
			"UppercaseLowercase" : "Majuscule/Minuscule",
			"Capitalize" : "Mettre des majuscules",
			"Uppercase" : "Majuscule",
			"Lowercase" : "Minuscule",
			"RoundedCorners" : "Coins arrondis",
			"Borders" : "Bordures",
			"Shadows" : "Ombres",
			"Shadow" : "Ombre",
			"BorderRadius" : "Rayon de la bordure",
			"BorderWidth" : "Largeur de la bordure",
			"BorderBottomWidth" : "Largueur de la bordure inférieure",
			"BorderTopWidth" : "Largueur de la bordure supérieure",
			"BorderRightWidth" : "Largeur du côté droit de la bordure",
			"BorderLeftWidth" : "Largeur du côté gauche de la bordure",
			"BorderColor" : "Couleur de la bordure",
			"PositionLeftCenterRight" : "Position gauche, centre, droite",
			"MinWidth" : "Largeur minimale",
			"MaxWidth" : "Largeur maximale",
			"MaxHeight" : "Hauteur maximale",
			"MinHeight" : "Hauteur minimale",
			"MarginTop" : "Marge supérieure",
			"MarginBottom" : "Marge inférieure",
			"MarginLeft" : "Marge à gauche",
			"MarginRight" : "Marge à droite",
			"PaddingTop" : "Espace supérieure",
			"PaddingBottom" : "Espace inférieure",
			"PaddingLeft" : "Espace à gauche",
			"PaddingRight" : "Espace à droite",
			"AlignItems" : "Aligner les éléments",
			"TitleStyle" : "Style du titre",
			"SubtitleStyle" : "Style des sous-titres",
			"ButtonStyle" : "Style de bouton",
			"PriceStyle" : "Style de prix",
			"TextStyle" : "Style de texte",
			"FigcaptionPosition" : "Position ou occultation des titres",
			"StoreSearchRow" : "Barre de recherche dans la boutique",
			"Height" : "Hauteur",
			"Width" : "Largeur",
			"Size" : "Taille",
			"IconBehaviour" : "Comportement des icônes",
			"IconLink" : "Lien (ouvrira votre lien)",
			"IconShare" : "Partager (ouvrira une fenêtre de partage)",
			"IconType" : "Type d'icône",
			"IconTitles" : "Texte",
			"Square" : "Carré",
			"Regular" : "Ordinaire",
			"ItemFit" : "Ajustement des éléments",
			"ItemMargin" : "Marge de l′élément",
			"ItemSize" : "Taille de l'élément",
			"ImageSize" : "Taille de l'image",
			"ReverseOrder" : "Inverser l’ordre",
			"OpenLightboxOnClick" : "Ouvrir la visionneuse quand on clique sur une miniature",
			"LightboxAnimation" : "Animation de visionneuse",
			"LightboxCaptionPlacement" : "Emplacement de la légende de la visionneuse",
			"LightboxImageFit" : "Ajustement de l'image de la visionneuse",
			"FullscreenCover" : "Couverture plein écran",
			"GoodForLongDesc" : "Adapté aux longues descriptions",
			"RearrangeElements" : "Réorganiser les éléments",
			"RearrangeElementsExp" : "Cliquez sur la touche ESC, lorsque vous avez terminé la réorganisation des éléments.",
			"MoveInsideBluBox" : "Déplacer les éléments à l'intérieur de l'espace bleu",
			"ClickEscToQuitMoving" : "Cliquez sur ESC pour quitter le déplacement",
			"AnimationOnEnter" : "Animation sur Entrée",
			"HoverEffect" : "Effet de survol",
			"AddNewElementBelow" : "Ajouter un élément ci-dessous",
			"SelectAFileFromComputer" : "Sélectionnez un fichier de votre ordinateur",
			"SelectFilesFromComputer" : "Sélectionnez des fichiers de votre ordinateur",
			"SupportedFileTypes" : "Types de fichiers pris en charge",
			"MaxFileSize" : "Taille maximale du fichier",
			"MaxNumberOfFiles" : "Nombre maximum de fichiers",
			"MaxNrOfFiles" : "Nombre maximum de fichiers",
			"ColorSpace" : "Espace couleur",
			"ImageScaling" : "Ajuster l’échelle de l’image",
			"Selected" : "Sélectionné",
			"UseSelectedImages" : "Utiliser les éléments sélectionnés",
			"UseTheImage" : "Utilisez l'élément",
			"UsedSpace" : "Espace utilisé",
			"BuyMoreSpace" : "Acheter plus d'espace",
			"SelectImagesFromLibrary" : "Sélectionner des images/vidéos dans votre mediathèque",
			"SelectImageFromLibrary" : "Sélectionner une image/vidéo dans votre mediathèque",
			"SelectImagesFromMobile" : "Sélectionner des images depuis un téléphone portable",
			"SelectImage" : "Sélectionner une image",
			"UploadImages" : "Télécharger des images",
			"StartUpload" : "Démarrer le téléchargement",
			"AFileIsAdded" : "Un fichier est ajouté",
			"ChangeFile" : "Changer le fichier",
			"UploadIsDone" : "Le téléchargement est terminé: effacer la liste",
			"LargestSide" : "Côté le plus grand",
			"AddVideo" : "Ajouter une vidéo",
			"DropImagesHere" : "Déposer vos images ici",
			"ImportVideos" : "Importez des vidéos",
			"Import" : "Importer",
			"VideoUrl" : "Url Vidéo",
			"VideoUrlExp" : "L'URL de la vidéo de l'un de ces services",
			"RecommendedServices" : "Services recommandés",
			"RecommendedServices2" : "Parce que vous pouvez masquer les contrôles, désactiver le son et utiliser la video en arrière-plan",
			"TheVideoCouldNotBeImported" : "La vidéo n'a pas pu être importée. Assurez-vous que vous avez le bon URL.",
			"TheCoverImageIsSmallWarning" : "La taille de l'image de couverture est si petite qu'elle sera floue. Voulez-vous quand même l'ajouter?",
			"ImportFrom" : "Importer à partir de",
			"CoverImage" : "Image de couverture",
			"ChangeCoverImage" : "Changer l'image de couverture",
			"AddNewCoverImage" : "Ajouter une nouvelle image de couverture",
			"TheVideoNeedsACover" : "La vidéo a besoin d'une image de couverture.",
			"CoverImageExp" : "L'image qui sera affichée avant la lecture de la vidéo.",
			"CoverImageExp2" : "L'image de couverture ne peut PAS être modifiée une fois la vidéo ajoutée.",
			"ImagesWillBePermanentlyDeleted" : "(Les images seront définitivement supprimées).",
			"ItemsDeletedAfter" : "Les images sont supprimées. ATTENTION! Vous devez également supprimer les images de vos galeries pour éviter les images brisées. (Les images peuvent être visualisées pendant une durée de 30 jours en raison du cache global.)",
			"YouCantAddVideosHere" : "Vous ne pouvez pas ajouter de vidéos ici. Sélectionnez un autre fichier.",
			"SeoTitle" : "Titre Seo",
			"SeoTitleExp" : "Le titre dans la fenêtre du navigateur et dans les moteurs de recherche.",
			"SeoDescription" : "Description Seo",
			"SeoDescriptionExp" : "La description vue dans les moteurs de recherche.",
			"OverruledByEntity" : "Remplacé par les paramètres de référencement de l'entité (page, publication ou produit).",
			"SeoKeywords" : "Mots-clés SEO",
			"SeoLanguage" : "Langue SEO",
			"SiteIcon" : "Icône du site",
			"SiteIconExp" : "La petite icône dans la fenêtre du navigateur. Important! Utilisez une image carrée au format .PNG et aux dimensions maximales",
			"ShareImage" : "Partager l'image",
			"ShareImageExp" : "L'image qui s'affiche lorsque votre site est partagé sur les réseaux sociaux. Taille min.",
			"DisableRightClick" : "Désactiver le clic droit",
			"DisableRightClickEsc" : "Désactive le clic droit sur votre site Internet et rend plus difficile le téléchargement des images. (Un clic droit fonctionnera toujours dans le panneau d'administration.)",
			"EnableCookieMessage" : "Activer le message de consentement aux cookies",
			"CookieMessageExp" : "Si un visiteur accepte les cookies, le message sera supprimé de son navigateur pendant 30 jours.",
			"CookieMessage" : "Corps de message du cookie",
			"EnableCookieMessageExp" : "Affichera un message cookie contextuel sur votre site Internet",
			"AddSampleMessage" : "Ajouter un exemple de message",
			"GoogleAnalyticsTrackingId" : "ID de suivi Google Analytics",
			"GoogleAnalyticsTrackingIdExp" : "Ajoutez Google Analytics à votre site Internet. Insérez l'ID de suivi ici.",
			"MetaVerification" : "Vérification Méta",
			"MetaVerificationExp" : "Pour vérifier que vous êtes le propriétaire du site internet. (Utilisé par Google Search Console, etc.)",
			"MetaName" : "Nom",
			"MetaNameExp1" : "Le texte à l'intérieur de l'attribut 'name' de la balise meta verification",
			"MetaNameExp2" : "Par exemple, si la balise comprend name='google-site-verification', insérez ci-dessous : google-site-verification",
			"MetaContent" : "Contenu",
			"MetaContentExp" : "Le texte à l'intérieur de l'attribut 'content' de la balise meta verification (Par exemple, si la balise comprend content='xxxyyyzzz', insérez ci-dessous : xxxyyyzzz)",
			"SaveMetaTag" : "Enregistrer la balise méta",
			"MetaTagDone" : "La balise méta est enregistrée et insérée dans votre site Live. (Elle ne peut pas être inspectée dans le panneau d'administration).",
			"MetaTagError" : "Vous devez ajouter le nom et le contenu de la balise méta.",
			"GoogleAnalyticsDone" : "L'identifiant Google Analytics est enregistré et Analytics est ajouté à votre site Live. (Il ne peut pas être inspecté dans le panneau d'administration).",
			"UnPublishSite" : "Annuler la publication de votre site",
			"UnPublishSiteExp" : "Votre site internet ne sera pas disponible en ligne. (Vous pourrez à nouveau publier votre site.)",
			"AreYouSureUnpublish" : "Êtes-vous sûr de vouloir annuler la publication de votre site Internet?",
			"SiteNotAvailable" : "Votre site n'est plus disponible en ligne.",
			"HideTheMenuOnThisPage" : "Masquer le menu sur cette page",
			"HideTheMenuOnThisPageConf" : "Êtes-vous sûr de vouloir supprimer le lien du menu?",
			"DuplicateThePage" : "Dupliquer la page",
			"DuplicateThePageExp" : "La page sera dupliquée. (Utile si vous voulez réutiliser des sections sur de nouvelles pages.)",
			"DuplicateThePageConf" : "Êtes-vous sûr de vouloir dupliquer cette page?",
			"DuplicateProductConf" : "Êtes-vous sûr de vouloir dupliquer ce produit ?",
			"DuplicateProductDone" : "Le produit est dupliqué.",
			"DuplicatePageDone" : "La page est dupliquée.",
			"UnPublishThePage" : "Annuler la publication de la page",
			"UnPublishThePageExp" : "Elle ne sera pas disponible sur votre site live . (Vous pourrez la publier à nouveau.)",
			"UnPublishThisConf" : "Êtes-vous sûr de vouloir désactiver la publication ?",
			"PublishAgain" : "Elle ne sera pas disponible sur votre site Live.",
			"DeleteThePage" : "Supprimer la page.",
			"DeleteThePageExp" : "La page sera définitivement supprimée.",
			"DeleteThePageConf" : "Êtes-vous sûr de vouloir supprimer cette page?",
			"DeleteTheMessageConf" : "Êtes-vous sûr de vouloir supprimer cette message ?",
			"AdminMenu" : "Menu admin.",
			"ManagePages" : "Gérer les pages",
			"BlogStoreClients" : "Blog | Boutique | Clients",
			"Settings" : "Paramètres",
			"OtherSettings" : "Autres paramètres",
			"Publish" : "Publier",
			"Upgrade" : "Mettre à jour",
			"SeeLive" : "Voir votre site",
			"CreateNewPage" : "Créer une nouvelle page",
			"EditExistingPages" : "Éditer les pages existantes",
			"ChangeStartPage" : "Changer la page de départ",
			"ManageYourBlog" : "Gérer votre blog",
			"ManageYourStore" : "Gérer votre boutique",
			"ManageClientGalleries" : "Gérer les galeries client",
			"StartStore" : "Créez votre boutique",
			"StartBlog" : "Créez votre blog",
			"DefaultStyles" : "Styles par défaut",
			"WebsiteSettings" : "Paramètres du site",
			"Translations" : "Traductions",
			"CustomCss" : "CSS personnalisé",
			"CustomCssExp1" : "Utilisez les outils de développement du navigateur pour explorer le marquage. Ajoutez votre code CSS ici.",
			"CustomCssExp2" : "À utiliser avec précaution! Si vous ajoutez un code défectueux ici, votre site Internet risque de ne plus fonctionner.",
			"AccountSettings" : "Paramètres du compte",
			"Subscription" : "Abonnement",
			"Messages" : "Messages",
			"Language" : "Langue",
			"Logout" : "Se déconnecter",
			"WhatTypeOfContent" : "Quel type de contenu souhaitez-vous ajouter?",
			"AdditionalSections" : "Sections supplémentaires",
			"CreateThisPage" : "Créer cette page",
			"PageTitle" : "Titre de la page",
			"AddToMenu" : "Ajouter au menu",
			"AddToMenuConf" : "Êtes-vous sûr de vouloir basculer le lien de menu sur cette",
			"CreatePage" : "Créer une page",
			"ThePageNeedsATitle" : "La page a besoin d'un titre",
			"TheEntityNeedsATitle" : "L'entité a besoin d'un titre",
			"EditSection" : "Modifier la section",
			"EditMenu" : "Éditer le menu",
			"EditPost" : "Modifier la publication",
			"EditStore" : "Éditer la boutique",
			"EditProduct" : "Éditer le produit",
			"EditImages" : "Éditer les images",
			"EditLinks" : "Modifier les liens",
			"AddNewSection" : "Ajouter une nouvelle section",
			"YourPages" : "Vos pages",
			"ViewAndEdit" : "Voir et Éditer",
			"View" : "Afficher",
			"StartPage" : "Page de départ",
			"TheCurrentStartPage" : "La page de départ actuelle de votre site",
			"SetOnePageAsStartPage" : "Définir l'une de vos pages comme page de départ",
			"SetThisAsStartPage" : "Définir cette page comme page de départ",
			"YourCurrentStartPage" : "Votre page de départ actuelle",
			"YourStartPageIsChanged" : "Votre page de départ est modifiée",
			"YourBlog" : "Votre blog",
			"BlogSettings" : "Paramètres du blog",
			"ViewBlog" : "Afficher le Blog",
			"AddNewPost" : "Ajouter un nouvel article",
			"ViewPost" : "Afficher la publication",
			"NewPost" : "Nouvelle publication",
			"PostSettings" : "Paramètres de la publication",
			"DisableComments" : "Désactiver les commentaires",
			"ManageComments" : "Gérer les commentaires de la publication",
			"ManageCommentsExp" : "Modifier ou supprimer des commentaires sur le post.",
			"PostComments" : "Poster un commentaire",
			"DeletePost" : "Supprimer une publication",
			"DeletePostExp" : "La publication sera définitivement supprimée.",
			"ShareButtons" : "Boutons Partager",
			"ShareButtonsBlogExp" : "Les boutons Partager s'afficheront sur chaque publication",
			"ShareButtonsProductExp" : "Les boutons Partager s'afficheront sur chaque produit",
			"UnPublishBlog" : "Annuler la publication de votre blog",
			"UnPublishBlogExp" : "Elle ne sera pas disponible sur votre site Internet en direct. Votre publication ne sera pas supprimée.",
			"UnPublishBlogConf" : "Êtes-vous sûr de vouloir annuler la publication de votre blog?",
			"ViewStore" : "Voir la Boutique",
			"YourStore" : "Votre boutique",
			"StoreSettings" : "Paramètres de la Boutique",
			"AddNewProduct" : "Ajouter un nouveau produit",
			"GeneralSettings" : "Paramètres généraux",
			"YourCompany" : "Votre société",
			"Payment" : "Paiement",
			"DiscountCodes" : "Codes promo",
			"Shipping" : "Livraison",
			"Taxes" : "Taxes",
			"Orders" : "Commandes",
			"NewProduct" : "Nouveau produit",
			"ViewProduct" : "Voir le produit",
			"ProductSettings" : "Paramètres du produit",
			"Variants" : "Variantes",
			"TrackInventory" : "Suivi de l'inventaire",
			"Inventory" : "Inventaire",
			"InventoryExp" : "Le nombre d'articles que vous avez dans votre boutique.",
			"DigitalFile" : "Fichier numérique",
			"Printing" : "Impression",
			"ReleaseDate" : "Date de diffusion",
			"EntityDateExp" : "Si vous ajoutez une date dans le futur, elle ne sera pas publiée sur votre site en direct avant cette date.",
			"Label" : "Label",
			"Categories" : "Catégories",
			"DiscountInPercent" : "Réduction en pourcent",
			"TrackInventories" : "Suivre les inventaires",
			"ThisProductIsNotTax" : "Ce produit n'est pas soumis à la taxe de vente",
			"DeleteProduct" : "Supprimer le produit",
			"DeleteProductExp" : "Le produit sera définitivement supprimé.",
			"AddNewVariant" : "Ajouter une nouvelle variante",
			"VariantsWhy" : "Offre différentes variantes de votre produit",
			"VariantsExample" : "Grand, moyen, petit",
			"SaveNewVariant" : "Enregistrer une nouvelle variante",
			"ThisIsAPhysicalProduct" : "Ceci est un produit physique",
			"WeightExp" : "Utilisé pour calculer les coûts d'expédition à la caisse.",
			"DigitalDownload" : "Téléchargement numérique",
			"DigitalDownloadExp" : "Autorise votre client à télécharger un fichier lorsque la commande est terminée.",
			"ShippingIsTurnedOff" : "L'expédition est désactivée pour le produit.",
			"Protection" : "Protection",
			"ProtectionExp" : "Le fichier est crypté et caché",
			"Currency" : "Monnaie",
			"CurrencyExp" : "La devise de votre boutique.",
			"ShareButtonsStoreExp" : "Les boutons Partager s'afficheront sur chaque publication",
			"StoreCategories" : "Catégories boutique",
			"StoreCategoriesExp" : "Les catégories qui apparaissent dans la ligne de recherche de la page Boutique.",
			"ReturnPolicy" : "Politique de retour",
			"ReturnPolicyAdd" : "Ajouter une politique de retour générique",
			"TermsAndConditions" : "Conditions générales",
			"TermsAndConditionsAdd" : "Ajouter un accord générique",
			"UnPublishStore" : "Annuler la publication de la boutique",
			"UnPublishStoreExp" : "Votre boutique ne sera pas disponible sur votre site en direct. (Vos produits ne seront pas supprimés.)",
			"PaymentMethod" : "Mode de paiement",
			"ManualPayment" : "Paiement manuel",
			"ManualPaymentExp" : "Cette option vous permet de gérer manuellement chaque commande. Après le paiement, votre client recevra vos instructions de paiement.",
			"AcceptPayment" : "Accepter les paiements",
			"CheckoutInstructions" : "Instructions de paiement",
			"CheckoutInstructionsExp" : "Fournir aux clients des instructions pour payer en dehors de votre boutique en ligne.",
			"CheckoutInstructionsAdd" : "Ajouter des instructions génériques",
			"EnablePaypalCheckout" : "Activez le paiement par PayPal",
			"EnablePaypalCheckoutExp" : "Le moyen le plus simple d'accepter des paiements. Créer simplement un compte PayPal et ajouter l'e-mail du compte.",
			"PayPalAccountEmail" : "Adresse email du compte PayPal",
			"AcceptCreditCard" : "Accepter les cartes de crédit",
			"AcceptCreditCardExp" : "Permet à votre client de payer avec une carte de crédit.",
			"AddNewDiscountCode" : "Ajouter un nouveau code de réduction",
			"DiscountCodeExp" : "Codes de réduction à utiliser lors du paiement pour obtenir la remise.",
			"DiscountCode" : "Code de réduction",
			"DiscountCodePboxExp" : "Si vous avez un code de réduction, veuillez le saisir ici.",
			"DiscountPercent" : "Pourcentage de la remise",
			"StartDate" : "Date de début",
			"EndDate" : "Date de fin",
			"AddShippingCostOnCheckout" : "Ajouter des frais d'expédition au paiement",
			"Disable" : "Désactiver",
			"CalculateBasedOnOrderWeight" : "Calculer le coût d'expédition en fonction du poids de la commande",
			"ShippingDisabled" : "Expédition désactivée",
			"ShippingDisabledExp" : "Après avoir reçu une commande, vous pouvez vérifier les frais d’expédition en fonction de la destination. Ensuite, vous devrez déclarer les frais d’expédition sur un reçu manuel.",
			"HowToAddShippingCost" : "Comment ajouter des frais d'expédition",
			"HowToAddShippingCostExp" : "Ajouter le poids à chaque article (Modifier le produit > paramètres > expédition). Le poids total d'une commande sera utilisé pour calculer les frais d'expédition.",
			"ShippingZones" : "Zones d'expédition",
			"AddNewShippingZone" : "Ajouter une nouvelle zone d'expédition",
			"EditShippingZone" : "Modifier la zone d'expédition",
			"ShippingWhy" : "Ajouter différents frais d'expédition pour différentes destinations.",
			"ToCountry" : "Vers Pays",
			"OrderWeight" : "Poids de la commande",
			"ShippingCost" : "Frais de livraison",
			"SaveNewZone" : "Enregistrer une nouvelle zone",
			"AddNewWeightRate" : "Ajouter un nouveau tarif au poids",
			"EditWeightRate" : "Mofifier le tarif au Poids",
			"MinimumOrderWeight" : "Poids minimum de commande",
			"MaximumOrderWeight" : "Poids maximum de commande",
			"EverywhereElse" : "Partout ailleurs",
			"DisableShippingToOtherLocations" : "Désactiver l'expédition vers d'autres destinations",
			"DisableShippingToOtherLocationsExp" : "Désactive l'expédition vers toutes les destinations qui ne sont pas spécifiquement ajoutées.",
			"TaxMethod" : "Méthode de taxe",
			"ManuallyHandleTaxes" : "traiter manuellement les taxes",
			"ChargeBasedOnLocation" : "Calcule la TVA au moment du paiement en fonction de l'emplacement du client",
			"HowToAddTaxes" : "Comment ajouter des taxes",
			"HowToAddTaxesExp" : "Ajouter un taux de TVA pour chaque pays/région où vous envisagez de vendre. La TVA sera calculée au moment du paiement.",
			"ManuallyHandleTaxesExp" : "La TVA n'est pas ajoutée au paiement. Après avoir reçu une commande, vous devrez calculer manuellement la TVA et envoyer au client un reçu à jour.",
			"TaxLocations" : "Taux de TVA",
			"AddNewTaxLocation" : "Ajouter un nouveau taux de TVA",
			"TaxLocationWhy" : "Ajouter différents taux de TVA pour différentes destinations.",
			"TaxPercent" : "Pourcentage de la TVA",
			"SaveNewLocation" : "Enregistrer la nouvelle destination",
			"DisableSalesToOtherLocations" : "Désactiver les ventes vers d'autres destinations",
			"DisableSalesToOtherLocationsExp" : "Désactive les ventes vers toutes les destinations qui ne sont pas spécifiquement ajoutées.",
			"CloseProductWithoutImageConf" : "Les articles sans images ne sont pas affichés dans votre boutique. Êtes-vous sûr de vouloir quitter sans ajouter d'image?",
			"AccountEmail" : "E-mail du compte",
			"AccountEmailExp" : "Utilisé pour se connecter et pour toutes les notifications sur votre site (messages, commentaires, commandes, sélections de clients, etc.).",
			"ChangeEmail" : "Modifier l'e-mail",
			"NewEmail" : "Nouvel e-mail",
			"AccountPassword" : "Mot de passe du compte",
			"AccountPasswordExp" : "Utilisé pour se connecter au panneau d'administration.",
			"ChangeAccountPassword" : "Modifier le mot de passe du compte",
			"NewPassword" : "Nouveau mot de passe",
			"OldPassword" : "Ancien mot de passe",
			"FirstName" : "Prénom",
			"LastName" : "Nom",
			"Profession" : "Profession",
			"Architect" : "Architecte",
			"Artist" : "Artiste",
			"MusicArtist" : "Artiste",
			"Designer" : "Designer",
			"MakeUpArtist" : "Styliste",
			"Model" : "Modèle",
			"Musician" : "Musicien(ne)",
			"Photographer" : "Photographe",
			"Retoucher" : "Retoucheur",
			"Store" : "Boutique",
			"Blog" : "Blog",
			"Post" : "Publication",
			"BlogTitle" : "Titre du blog",
			"StartYourBlog" : "Commencer votre blog",
			"StartYourStore" : "Commencer votre boutique",
			"StoreTitle" : "Titre de la boutique",
			"Student" : "Étudiant",
			"Other" : "Autre",
			"UnsubscribeTo" : "Se désabonner de",
			"NewsEmails" : "Newsletter",
			"CampaignEmails" : "Campagne publicitaire ",
			"CustomerCareEmails" : "Email du service client",
			"TermsOfService" : "Conditions Générales d'Utilisation",
			"TermsOfServiceExp" : "Si vous utilisez Portfoliobox, vous acceptez ces conditions d'utilisation.",
			"GeneralTerms" : "Conditions générales",
			"PrivacyPolicy" : "Politique de confidentialité",
			"DeleteTheAccount" : "Supprimer le compte",
			"DeleteTheAccountExp" : "Tout le contenu et les images seront définitivement supprimés.",
			"PleaseLetUsKnowWhy" : "N'hésitez pas à nous faire savoir pourquoi",
			"YourPlan" : "Votre offre",
			"RestoreYourPremiumAccount" : "Restaurer votre compte Premium",
			"AreYouSureToRestore" : "Êtes-vous sûr de vouloir restaurer votre compte premium?",
			"YourAccountWillNotBeDowngraded" : "Votre compte ne sera pas modifié",
			"ClientImages" : "Images des galeries client",
			"ClientGalleryImages" : "Images des galeries client",
			"ReceiptInformation" : "Informations sur les reçus",
			"ReceiptInfoExp" : "Si vous souhaitez inclure votre nom et votre adresse sur les reçus, ajoutez-les ici.",
			"VatNr" : "Numéro de TVA",
			"ChangeCard" : "Modifier la carte",
			"UseAnotherCard" : "Utiliser une autre carte pour vos paiements",
			"VatNrExp" : "Pour les entreprises de l'UE avec un numéro de TVA valide. Entrez votre numéro de TVA et cliquez sur Valider.",
			"SubmitVat" : "Valider",
			"SubmitVatError" : "Votre TVA n'a pas été enregistrée car votre numéro de TVA n'a pas été validé. Veuillez essayer un format différent.",
			"YourTransactions" : "Vos transactions",
			"YourTransactionsExp" : "Afficher le reçu pour le télécharger ou l'imprimer",
			"ViewInvoice" : "Afficher le reçu",
			"TheVATWasSaved" : "La TVA a été enregistrée",
			"YourCurrentPlan" : "Votre offre actuel",
			"MostPopular" : "Le plus populaire",
			"CustomerSupport" : "Service client",
			"FreeDomain" : "Domaine gratuit",
			"ForExample" : "par exemple",
			"Yournamecom" : "votrenom.com",
			"NoPortfolioboxLink" : "Pas de lien Portfoliobox",
			"NextPayment" : "Prochain paiement",
			"YourAccountWillBeDowngraded" : "Votre compte passera à l'offre inférieure",
			"Month" : "Mois",
			"Year" : "An",
			"UpgradeTo" : "Passer à l'offre",
			"IncludedIn" : "compris dans",
			"OneYear" : "Annuel",
			"OneYearExp" : "Vous économisez en payant annuellement",
			"MoneyBackGuarantee" : "Garantie satisfait ou remboursé",
			"Off" : "Désactivé",
			"Monthly" : "Mensuel",
			"MonthlyExp" : "L'offre la plus flexible.",
			"TotalPriceFor1Year" : "Prix total pour 1 an",
			"WhatYouWillPayNow" : "Ce que vous paierez maintenant",
			"BilledYearly" : "Facturation annuelle",
			"BilledMonthly" : "Facturation mensuelle",
			"YourDiscount" : "Votre remise",
			"LeftOfPlan" : "La période non-utilisée de votre abonnement sera appliquée en réduction.",
			"ThatsTheSmallestAmount" : "C'est le montant minimum. Le reste de la réduction est sauvegardé et appliqué aux autres paiements.",
			"Pay" : "Payer",
			"NewDomain" : "Nouveau domaine",
			"ExistingDomain" : "Domaine existant",
			"GetANewDomain" : "Choisir un nouveau domaine pour mon site",
			"GetANewDomainExp" : "Le domaine est l'adresse de votre site internet.",
			"GetANewDomainExp2" : "Par exemple votrenom.com ou votrenom.pb.design",
			"GetANewDomainBtn" : "Choisir un nouveau domaine",
			"IAlreadyHaveADomain" : "J'ai déjà un domaine",
			"IAlreadyHaveADomainExp" : "Si vous possédez déjà un domaine (avec un autre fournisseur), vous pouvez le connecter à votre site Portfoliobox.",
			"IAlreadyHaveADomainBtn" : "Utiliser le domaine que je possède déjà",
			"SearchForAnAvailableDomain" : "Rechercher un domaine disponible",
			"ProDomains" : "Domaines Pro",
			"FreeDomains" : "Domaines gratuits",
			"GetIt" : "OK!",
			"IncludedInProPlan" : "Inclus dans l'offre PRO",
			"UpgradeNow" : "Passer à l'offre supérieure maintenant",
			"ItsAvailable" : "Disponible!",
			"UseItForMyWebsite" : "Utilisez-le pour mon site internet",
			"GotIt" : "J'ai compris!",
			"YourSiteHasANewDomain" : "Votre site a un nouveau domaine",
			"YourDomainName" : "Votre nom de domaine",
			"YourDomainNameExp" : "Entrez votre domaine actuel. (NB! Vous devrez configurer ce domaine pour que votre site Internet fonctionne.)",
			"mydomaincom" : "mondomaine.com",
			"UseMyDomain" : "Utiliser mon domaine",
			"DomainShortError" : "Le domaine doit comporter au moins 4 caractères.",
			"NoDotError" : "Votre domaine n'a pas de point.",
			"IsItYourDomain" : "Est-ce votre domaine?",
			"DoYouWantToUseThisDomainForYourSite" : "Voulez-vous utiliser ce domaine pour votre site?",
			"IsThisYourDomain" : "S’agit-il de votre domaine?",
			"YesUseIt" : "Oui!",
			"UsingYourOwnDomain" : "Utiliser votre propre domaine",
			"ThankYou" : "Merci!",
			"TheActionWasSuccessful" : "Exécution réussie !",
			"ConfigureYourDomain" : "Configurez votre domaine",
			"ConfigureYourDomainExp" : "Configurez votre domaine pour que votre site Internet fonctionne.",
			"ReadHow" : "Voir les explications",
			"ContactUs" : "Nous contacter",
			"CantMakeItWork" : "Je n'y arrive pas",
			"GetANewDomainInstead" : "Choisir un nouveau domaine",
			"IHaveConfiguredMyDomain" : "J'ai configuré mon domaine.",
			"AreYouSureThatTheDomainIsConf" : "Êtes-vous sûr que le domaine est configuré?",
			"Configured" : "Configuré",
			"ConfiguredError" : "Désolé! Le domaine n'est pas configuré correctement. Veuillez nous contacter via le chat en bas de votre écran.",
			"GetANewProDomain" : "Obtenir un nouveau domaine Pro",
			"SetUpTheDomain" : "Configurer le domaine",
			"WeAreSettingUpYourDomain" : "Nous configurons votre domaine",
			"ItWillBeReadyInAFewHours" : "Vous recevrez un email dans quelques heures, lorsque le domaine sera prêt.",
			"VisitYourSite" : "Visitez votre site",
			"MarketYourSiteAndAdd" : "Faites la promotion de votre site et ajoutez-le à Google",
			"MarketYourSiteAndAddExp" : "Google trouvera automatiquement votre site s’il contient des liens.",
			"MarketYourSiteAndAddExp2" : "Plus de liens = Meilleur classement Google = Plus de visiteurs",
			"PostInSm" : "Publier sur les réseaux sociaux",
			"AskOthers" : "Demander aux autres de partager",
			"WriteInForums" : "Écrire dans les forums, blogs, etc",
			"ShareNow" : "Partager maintenant",
			"CheckoutMyWebsite" : "Vérifier mon site Internet",
			"AreYouSureYouWantToResetAllDefault" : "Êtes-vous sûr de vouloir réinitialiser les styles par défaut?",
			"EditShareButton" : "Éditer le bouton de partage",
			"AddNewShareButton" : "Ajouter un nouveau bouton de partage",
			"SaveShareButton" : "Enregistrer le bouton de partage",
			"AddNewTag" : "Ajouter un nouveau tag",
			"EditTag" : "Modifier le tag",
			"SaveNewTag" : "Enregistrer le tag",
			"AddNewField" : "Ajouter un nouveau champ",
			"SaveNewField" : "Enregistrer le champ",
			"AddNewOption" : "Ajouter une nouvelle option",
			"EditOption" : "Modifier l’option",
			"WhatDoYouWantToLinkTo" : "À quoi voulez-vous la lier?",
			"EditSublink" : "Modifier le sous-lien",
			"AddNewMenuLink" : "Ajouter un nouveau lien au menu",
			"SaveMenuLink" : "Enregistrer le lien du menu",
			"Sublinks" : "Sous-liens",
			"AddNewSublink" : "Ajouter un nouveau sous-lien",
			"MenuLinksAreTheSameAsPages" : "NB! Les liens du menu ne sont pas des Pages. Vous pouvez gérer vos pages depuis le menu en haut à gauche.",
			"CloseTheDialog" : "Fermer cette boîte de dialogue et voir le menu principal",
			"AddNewCategory" : "Ajouter une nouvelle catégorie",
			"SaveCategory" : "Enregistrer la catégorie",
			"YouNeedATitle" : "Vous devez ajouter un titre",
			"IfYouChangeCategory" : "Si vous changez de catégorie, vous devrez modifier tous les produits utilisant cette catégorie.",
			"AddNewLink" : "Ajouter un nouveau lien",
			"SaveLink" : "Enregistrer le lien",
			"AddSocialLink" : "Ajouter un lien social",
			"AddExperience" : "Ajouter une expérience",
			"SaveExperience" : "Enregistrer l'expérience",
			"AddNewSkill" : "Ajouter une nouvelle compétence",
			"SaveSkill" : "Enregistrer la compétence",
			"AddNewPerson" : "Ajouter une nouvelle personne",
			"SavePerson" : "Enregistrer la personne",
			"SaveEmails" : "Enregistrer les emails",
			"AddNewService" : "Ajouter un nouveau service",
			"SaveService" : "Enregistrer le service",
			"AddTestimonial" : "Ajouter un témoignage",
			"SaveTestimonial" : "Enregistrer le témoignage",
			"AddNewLogo" : "Ajouter un nouveau logo",
			"SaveLogo" : "Enregistrer le logo",
			"ChangeToImageLogo" : "Choisissez un logo image",
			"RemoveImageAndChangeToText" : "Supprimer l'image et ajouter une logo texte",
			"ChangeToTextLogo" : "Modification du texte du logo",
			"ImageHeight" : "Hauteur de l'image",
			"WhichBlogPostsToDisplay" : "Quels articles de blog voulez-vous afficher?",
			"TheMostResentPosts" : "Les publications les plus récentes",
			"PostWithTag" : "Publications avec un certain tag",
			"TheTag" : "Le Tag",
			"TheTagExp" : "Écrivez le tag à partir duquelle vous souhaitez sélectionner la publication",
			"HowManyPosts" : "Combien de publications souhaitez-vous afficher?",
			"LimitsPostsInSection" : "Limite du nombre de publications dans cette section.",
			"WhichProductsToDisplay" : "Quels articles voulez-vous afficher?",
			"TheMostRecentProducts" : "Les articles les plus récents",
			"ProductsWithDiscount" : "Tous les articles avec des rabais",
			"ProductsWithCategory" : "Articles d'une certaine catégorie",
			"HowManyProducts" : "Combien d'articles voulez-vous afficher?",
			"LimitsNumberOfProducts" : "Limite le nombre d'articles dans cette section",
			"FromCategory" : "De la catégorie",
			"UpgradeToChangeDomain" : "Passez à l'offre supérieure pour changer de domaine",
			"APremiumDomainIsIncluded" : "Un domaine premium est inclus dans votre plan",
			"YouHaveReachedPageQuota" : "Vous avez atteint votre quota de pages. Passez à l'offre supérieure pour ajouter plus de pages.",
			"YouHaveReachedQuotaPro" : "Vous avez atteint votre quota. Veuillez contacter le service client pour obtenir plus d'espace.",
			"AreYouSureToPublishSiteAgain" : "Êtes-vous sûr de vouloir publier à nouveau votre site Internet?",
			"YourSiteIsAvailableAgain" : "Votre site est maintenant disponible en ligne.",
			"AreYouSureYouWantToLogout" : "Êtes-vous sûr de vouloir vous déconnecter?",
			"ChoseTemplate" : "Choisir un modèle",
			"ChoseNewTemplate" : "Choisir un nouveau modèle",
			"ChoseMenuTemplate" : "Choisir un modèle de menu",
			"TypeOfTemplate" : "Type de modèle",
			"CurrentlySelected" : "Actuellement sélectionné",
			"AreYouSureHideTheMenu" : "Êtes-vous sûr de vouloir masquer le menu sur cette page?",
			"YouCanActivateMenu" : "Vous pouvez réactiver le menu à partir des paramètres de page.",
			"CantDeleteLastSection" : "Vous ne pouvez pas supprimer la dernière section de la page.",
			"DeleteThePageOrAddSection" : "Supprimez la page (Gérer les pages > Paramètre de page > Supprimer) ou ajoutez une nouvelle section avant de la supprimer.",
			"DeleteElementConf" : "Êtes-vous sûr de vouloir supprimer cet élément?",
			"ChangeContent" : "Modifier le contenu",
			"EditMenuLinks" : "Modifier les liens du menu",
			"ChangeTemplate" : "Modifier le modèle",
			"ImageSizeAndStyle" : "Taille et styles de l'image",
			"VideoSettings" : "Paramètres vidéo",
			"TitlesSizeAndStyle" : "Tailles et styles des titres",
			"IconStyleBehaviour" : "Style et comportement des icônes",
			"BarColors" : "Couleur de la barre",
			"ShowHide" : "Afficher/masquer la barre de recherche",
			"LightboxSettings" : "Paramètres de visionneuse",
			"ColorsFonts" : "Couleurs et polices",
			"SizeMargins" : "Taille, marges et positions",
			"GalleryWidthBorders" : "Largeur et bordures de la galerie",
			"ReorderSections" : "Réorganiser les sections",
			"RemoveSamplesConf" : "Voulez-vous supprimer les échantillons?",
			"ReadyToUpgrade" : "Prêt(e) à passer à l'offre supérieure ?",
			"ShowMeTheOptions" : "Montrez-moi les options",
			"YourFirstPage" : "Votre première page!",
			"AddYourContent" : "Ajoutez votre propre contenu.",
			"LetsEditTheContent" : "Modifions le contenu",
			"TouchAndHold" : "Maintenir appuyé",
			"TapAndHoldExp" : "Tapez et maintenez n'importe quelle image, texte ou autre élément à modifier (ou cliquez sur les boutons de modification).",
			"TouchAndHoldBtn" : "Touchez et maintenez pour modifier",
			"WelcomeToPortfoliobox" : "Bienvenue à Portfoliobox!",
			"Start3steps" : "Commençons par une introduction en 3 étapes",
			"LetsStart" : "C'est parti",
			"StartByAddingPages" : "Commencez par ajouter vos pages. Vous pouvez ajouter des galeries, des pages et bien plus",
			"ClickHereToSetupBlog" : "Cliquez ici pour configurer votre blog, votre boutique et vos galeries de clients protégées par mot de passe",
			"PublishWebiste" : "Publiez votre site Internet et configurez votre domaine",
			"NextStepAddPage" : "La prochaine étape consiste à Ajouter votre première page.",
			"YouAreReady" : "Vous êtes prêt!",
			"ReachedBlogQuota" : "Vous avez atteint votre quota d'articles de blog. Passez à la version supérieure pour ajouter plus d'articles.",
			"ReachedProductQuota" : "Vous avez atteint votre quota de produits. Passez à la version supérieure pour ajouter plus d'articles",
			"ReloadAdminExp" : "Vous devez actualiser le panneau d'administration pour que cette modification soit prise en compte (actualiser votre navigateur).",
			"EmailsCantBeEmpty" : "Les adresses emails ne peuvent pas être vides",
			"TheEmailWasSent" : "Les emails ont été envoyés.",
			"OneOrMoreEmailIsNotCorrect" : "Une ou plusieurs adresses email ne sont pas correctes",
			"AreYouSureThatYouWantToEmail" : "Êtes-vous sûr de vouloir envoyer cette galerie par email à votre client?",
			"LoginWithLink" : "Connectez-vous via le lien ci-dessous pour accéder aux images. Vous pouvez les commenter et sélectionner celles que vous souhaitez commander.",
			"ShareWithClient" : "Partager avec votre client",
			"ClientEmails" : "Adresses email des clients",
			"EmailAddressesSeparated" : "Adresses email séparées par une virgule",
			"PasswordNeededForGallery" : "Mot de passe nécessaire pour accéder à la galerie.",
			"OtherInfoToClient" : "Autres informations que vous souhaitez envoyer à votre client.",
			"YourMessageToClient" : "Votre message au client",
			"TheMessageWasSent" : "Le message a été envoyé. Vous pouvez fermer la boîte de dialogue",
			"SendToClient" : "Envoyer au client",
			"ClientGalleryIncludingAllImages" : "Galerie client incluant toutes les images",
			"ReachedImageQuota" : "Vous avez atteint votre quota d'images. Mettez à niveau pour ajouter plus d'images.",
			"ReachedImageQuotaPro" : "Vous avez atteint votre quota d'images. Contactez-nous pour obtenir des images supplémentaires.",
			"NewClientGallery" : "Nouvelle galerie client",
			"ViewGallery" : "Voir la galerie",
			"EditClientGallery" : "Modifier la galerie client",
			"WatermarkImages" : "Images en filigrane",
			"AddAWaterMarkText" : "Ajouter un filigrane aux nouvelles images téléchargées dans la galerie",
			"WatermarkText" : "Texte du filigrane",
			"TheTextAddedToImages" : "Le texte qui est ajouté sur les images.",
			"ClientGalleries" : "Galeries client",
			"AddNewClientGallery" : "Ajouter une nouvelle galerie client",
			"YourEmailIsNotWorking" : "Votre email ne fonctionne pas. Veuillez le changer dès que possible dans Paramètres > Compte.",
			"YourBrowserIsOld" : "Votre navigateur est ancien et certaines fonctionnalités de Portfoliobox pourraient ne pas fonctionner. Veuillez télécharger la dernière version de votre navigateur.",
			"YourStartPage" : "Votre page d'accueil",
			"OneOfYourPages" : "Une de vos pages",
			"AnExternalLink" : "Un lien externe",
			"AnEmailAddress" : "Un email",
			"ScrollToTop" : "Défilement vers le haut de la page",
			"ScrollToASectionOnThisPage" : "Défilement vers une section de cette page",
			"LinkToYourStartPage" : "Lien vers votre page d'accueil",
			"LinkToYourBlog" : "Lien vers votre blog",
			"LinkToYourStore" : "Lien vers votre boutique",
			"ExternalUrl" : "URL externe",
			"LinkToThisUrl" : "Lien vers cet URL",
			"EmailAddress" : "Un email",
			"LinkToThisEmail" : "Lien vers cet email",
			"LinkToThis" : "Lier à",
			"YouCanAddPagesInfo" : "Vous pouvez ajouter de nouvelles pages à partir du menu principal, voir Gérer les pages.",
			"CloseAndGoToPages" : "Fermez cette boîte de dialogue et allez à Ajouter une nouvelle page",
			"SectionsOnThisPage" : "Les sections de cette page",
			"IncludeAllStates" : "Inclure tous les états",
			"PasswordErrorLength" : "Votre mot de passe doit comporter au moins 8 caractères",
			"PasswordErrorLetter" : "Votre mot de passe doit contenir au moins une lettre",
			"PasswordErrorDigit" : "Votre mot de passe doit contenir au moins un chiffre.",
			"PasswordErrorOld" : "Mauvais mot de passe! Essayez à nouveau.",
			"PasswordWasChanged" : "Le mot de passe a été changé.",
			"EmailNotValid" : "Ceci n'est pas un email valide. Veuillez saisir un email.",
			"TheEmailWasChanged" : "L'email a été changé.",
			"CssIsSaved" : "Le CSS est enregistré",
			"WrongPassword" : "Mot de passe incorrect ! Essayez à nouveau.",
			"TheAccountWillBeDeleted" : "Votre compte sera supprimé. Veuillez vous déconnecter.",
			"TheAccountWillBeDowngraded" : "Le compte passera à l'offre ",
			"ChoseABasicDomain" : "Choisir un domaine basic afin de passer à une offre inférieure",
			"YouCantKeepPremium" : "Vous ne pouvez pas garder votre domaine premium",
			"WhatPlanDoYouWantToDowngradeTo" : "Quel plan souhaitez-vous choisir?",
			"Downgrade" : "Passer à une offre inférieure",
			"PleaseLetUsKnowWhyDowngrade" : "Merci de nous indiquer pourquoi vous souhaitez passer à une offre inférieure",
			"DowngradeAccount" : "Passer à une offre inférieure pour ce compte",
			"AdminLanguage" : "Langue du panneau d'administration",
			"WhyNeedToUpgradeExp" : "Pourquoi passer à l'offre supérieure ? Vous avez déjà un compte PRO. Veuillez contacter le service client pour résoudre ce problème.",
			"YourPurchaseWasSuccessfull" : "Votre achat a été validé",
			"EditHeader" : "Modifier le titre",
			"EditText" : "Modifier le texte",
			"EditForm" : "Modifier le formulaire",
			"EditCategories" : "Modifier les catégories",
			"EditPrice" : "Modifier le tarif",
			"EditSubtitle" : "Modifier le sous-titre",
			"EditGallery" : "Modifier la galerie",
			"EditLink" : "Modifier le lien",
			"EditMusic" : "Modifier la Musique",
			"Track" : "Piste",
			"Length" : "Longueur",
			"AddNewTrack" : "Ajouter une nouvelle piste",
			"SaveTrack" : "Enregistrer la piste",
			"SelectTack" : "Sélectionner une piste",
			"ImportNewTrack" : "Importer une nouvelle piste",
			"ImportNewTrackExp" : "Coller l'URL de la piste à partir de l'un des services suivants",
			"ImportAndSelectTrack" : "Importer et sélectionner une piste",
			"ImportTrackFrom" : "importer une piste",
			"TheTrackWasImported" : "La piste a été importée",
			"TheTrackWasDeleted" : "La piste a été supprimée",
			"EditLinkPage" : "Modifier le lien de la page",
			"EditSocialMedia" : "Modifier les Réseaux sociaux",
			"EditList" : "Modifier la liste",
			"EditSkills" : "Modifier les Compétences",
			"SaveSocialMedia" : "Enregistrer le lien de réseau social",
			"EditTeam" : "Modifier l'Équipe",
			"Persons" : "Personnes",
			"EditServices" : "Modifier les Services",
			"Services" : "Services",
			"EditTestimonials" : "Modifier les Témoignages",
			"EditLogos" : "Modifier les Logos",
			"Testimonials" : "Témoignages",
			"Logos" : "Logos",
			"TextAndContacts" : "Texte et contacts",
			"text" : "Texte et contacts",
			"Gallery" : "Galerie",
			"LinkPage" : "Liens",
			"Service" : "Services",
			"Team" : "Équipe",
			"CoverPage" : "Page de couverture",
			"Cv" : "Cv",
			"Music" : "Musique",
			"MenuSection" : "Sous-menu",
			"Footer" : "Bas de page",
			"Action" : "Action",
			"EditDiscountCode" : "Modifier le code promo",
			"ToggleMenuConf" : "Êtes-vous sûr de vouloir afficher le menu sur cette page?",
			"SendAnEmailWithTheFile" : "Envoyer un courriel avec le fichier à votre propre adresse électronique",
			"YourCompanyName" : "Le nom de votre société",
			"SubGroups_thumb" : "Miniatures",
			"SubGroups_horizontal" : "Horizontal",
			"SubGroups_vertical" : "Vertical",
			"SubGroups_slideshow" : "Diaporama",
			"SubGroups_text" : "Texte",
			"SubGroups_image" : "Image",
			"SubGroups_contact" : "Contacts",
			"SubGroups_cover" : "Couverture",
			"SubGroups_cv" : "CV",
			"SubGroups_music" : "Musique",
			"SubGroups_social" : "Social",
			"SubGroups_list" : "Liste",
			"SubGroups_row" : "Rangée",
			"SubGroups_footer" : "Bas de page",
			"SubGroups_action" : "Action",
			"SubGroups_testimonials" : "Témoignages",
			"SubGroups_logos" : "Logos",
			"SubGroups_other" : "Autre",
			"MenuSubGroups_top" : "Haut",
			"MenuSubGroups_left" : "Gauche",
			"MenuSubGroups_hidden" : "Caché",
			"ContextMenuHeader_Border" : "Modifier la bordure",
			"ContextMenuHeader_Button" : "Modifier le Bouton",
			"ContextMenuHeader_BlogButton" : "Modifier le bouton du blog",
			"ContextMenuHeader_CaptionTitle" : "Modifier le titre",
			"ContextMenuHeader_CaptionSubTitle" : "Modifier le sous-titre",
			"ContextMenuHeader_CaptionText" : "Modifier le texte",
			"ContextMenuHeader_CaptionButton" : "Modifier le Bouton",
			"ContextMenuHeader_Column" : "Modifier la colonne",
			"ContextMenuHeader_Columns" : "Modifier les colonnes",
			"ContextMenuHeader_CvList" : "Modifier la liste",
			"ContextMenuHeader_Form" : "Modifier le formulaire",
			"ContextMenuHeader_Gallery" : "Modifier la galerie",
			"ContextMenuHeader_Header" : "Modifier l'entête",
			"ContextMenuHeader_Link" : "Modifier le lien",
			"ContextMenuHeader_Links" : "Modifier les liens",
			"ContextMenuHeader_LinkPage" : "Modifier les liens de la page",
			"ContextMenuHeader_Logo" : "Modifier le Logo",
			"ContextMenuHeader_LongText" : "Modifier le texte",
			"ContextMenuHeader_MainMenu" : "Modifier le menu",
			"ContextMenuHeader_MainMenuLinks" : "Éditer les liens du menu",
			"ContextMenuHeader_Page" : "Modifier la page",
			"ContextMenuHeader_Section" : "Modifier la section",
			"ContextMenuHeader_ShortText" : "Modifier le texte",
			"ContextMenuHeader_Service" : "Modifier le service",
			"ContextMenuHeader_Logos" : "Modifier les Logos",
			"ContextMenuHeader_Testimonials" : "Modifier les Témoignages",
			"ContextMenuHeader_SingleImage" : "Modifier l'image",
			"ContextMenuHeader_SingleImageBg" : "Modifier l'image",
			"ContextMenuHeader_Skills" : "Modifier les compétences",
			"ContextMenuHeader_Slideshow" : "Modifier le diaporama",
			"ContextMenuHeader_SocialMedia" : "Modifier les réseaux sociaux",
			"ContextMenuHeader_BlogPost" : "Modifier la publication du blog",
			"ContextMenuHeader_BlogHeader" : "Modifier le titre du blog",
			"ContextMenuHeader_BlogDate" : "Modifier la date du blog",
			"ContextMenuHeader_BlogText" : "Modifier le texte du blog",
			"ContextMenuHeader_BlogTags" : "Modifier les tags du blog",
			"ContextMenuHeader_BlogShare" : "Modifier les paramètres de partage du blog",
			"ContextMenuHeader_BlogCommentIcon" : "Modifier l'icône de commentaire",
			"ContextMenuHeader_Store" : "Modifier la boutique",
			"ContextMenuHeader_Product" : "Modifier le produit",
			"ContextMenuHeader_ProductCategories" : "Modifier les catégories de produits",
			"ContextMenuHeader_ProductButton" : "Modifier le bouton ajouter au panier",
			"ContextMenuHeader_ProductVariants" : "Modifier les variantes",
			"ContextMenuHeader_ProductBreadCrumbs" : "Éditer le fil d'Ariane",
			"ContextMenuHeader_ProductShare" : "Modifier les paramètres de partage de produit",
			"ContextMenuHeader_ProductHeader" : "Modifier le titre du produit",
			"ContextMenuHeader_ProductSubHeader" : "Modifier le sous-titre du produit",
			"ContextMenuHeader_ProductText" : "Modifier la description du produit",
			"ContextMenuHeader_ProductFigureTitle" : "Modifier les titres de l'image",
			"ContextMenuHeader_ProductFigureSubTitle" : "Modifier le sous-titre de l'image",
			"ContextMenuHeader_ProductPrice" : "Modifier le tarif",
			"ContextMenuHeader_StoreHeader" : "Modifier le titre de la boutique",
			"ContextMenuHeader_StoreText" : "Modifier la description de la boutique",
			"ContextMenuHeader_StoreFigureTitle" : "Modifier les titres des produits",
			"ContextMenuHeader_StoreFigurePrice" : "Modifier les prix des produits",
			"ContextMenuHeader_StoreFilterRow" : "Modifier les filtres de la boutique",
			"ContextMenuHeader_StoreCategories" : "Modifier les catégories de la boutique",
			"ContextMenuHeader_ClientGallery" : "Modifier la galerie client",
			"ContextMenuHeader_ClientGalleryHeader" : "Modifier le titre",
			"ContextMenuHeader_ClientGalleryDate" : "Modifier la date",
			"ContextMenuHeader_ClientGalleryText" : "Modifier le texte",
			"ContextMenuHeader_ClientGallerySearchRow" : "Modifier la barre de recherche",
			"ContextMenuHeader_ClientGallerySelectRow" : "Sélectionner une barre de recherche",
			"ContextMenuHeader_ClientGalleryFigureTitle" : "Modifier les titres",
			"ContextMenuHeader_ClientGalleryIcons" : "Modifier les titres",
			"ContextMenuHeader_Menu" : "Modifier le sous-menu",
			"ContextMenuHeader_Footer" : "Modifier le pied de page",
			"ContextMenuHeader_Action" : "Modifier l'action",
			"ContextMenuHeader_Team" : "Modifier l'Équipe",
			"ContextMenuHeader_Post" : "Modifier la publication",
			"ContextMenuHeader_Music" : "Éditer Musique",
			"ProductSettings_general" : "Paramètres généraux",
			"ProductSettings_variants" : "Variantes",
			"ProductSettings_shipping" : "Livraison",
			"ProductSettings_digitalfile" : "Fichier numérique",
			"ProductSettings_printing" : "Impression",
			"StoreSettings_general" : "Paramètres généraux",
			"StoreSettings_company" : "Votre société",
			"StoreSettings_payment" : "Paiement",
			"StoreSettings_discounts" : "Réductions",
			"StoreSettings_shipping" : "Livraison",
			"StoreSettings_taxes" : "Taxes",
			"StoreSettings_orders" : "Commandes",
			"DefaultStyles_Page" : "Général",
			"DefaultStyles_Section" : "Sections",
			"DefaultStyles_Header" : "Titres",
			"DefaultStyles_LongText" : "Paragraphes",
			"DefaultStyles_Links" : "Liens",
			"DefaultStyles_CaptionTitle" : "Titres de la légende",
			"DefaultStyles_CaptionSubTitle" : "Sous-titres des légendes",
			"DefaultStyles_Button" : "Boutons",
			"DefaultStylesMobile_Header" : "Titres",
			"DefaultStylesMobile_LongText" : "Paragraphes",
			"DefaultStylesMobile_CaptionTitle" : "Titres de la légende",
			"DefaultStylesMobile_CaptionSubTitle" : "Sous-titres des légendes",
			"Template_menu1" : "Menu 1",
			"Template_blank" : "Basic",
			"Template_blank2" : "Basic 2",
			"Template_shortinfo" : "En bref",
			"Template_shortinfo2" : "En bref 2",
			"Template_imageleft" : "Image à gauche",
			"Template_imageleft2" : "Image à gauche 2",
			"Template_imageright" : "Image à droite",
			"Template_imageright2" : "Image à droite 2",
			"Template_goldenratio" : "Nombre d'or",
			"Template_portraitratio" : "Portrait",
			"Template_squareratio" : "Carré",
			"Template_evenrows" : "Largeur fixe",
			"Template_cv1" : "CV 1",
			"Template_cv2" : "CV 2",
			"Template_halfscreencv" : "CV demi-écran",
			"Template_coverblank" : "Couverture basic",
			"Template_cover1" : "Couverture 1",
			"Template_cover2" : "Couverture 2",
			"Template_cover3" : "Couverture 3",
			"Template_cover4" : "Couverture 4",
			"Template_cover5" : "Couverture 5",
			"Template_cover6" : "Couverture 6",
			"Template_cover7" : "Couverture 7",
			"Template_cover8" : "Couverture 8",
			"Template_coverform" : "Formulaire en couverture",
			"Template_halfscreen" : "Demi-écran",
			"Template_halfscreenright" : "Demi-écran à droite",
			"Template_formright" : "Formulaire à droite",
			"Template_formright2" : "Formulaire à droite 2",
			"Template_contactcenter" : "Contact au centre",
			"Template_imagetop" : "Image en haut",
			"Template_imagebottom" : "Image en bas",
			"Template_imagetop2" : "Image en haut 2",
			"Template_textfullscreen1" : "Plein écran 1",
			"Template_textfullscreen2" : "Plein écran 2",
			"Template_textfullscreen3" : "Plein écran 3",
			"Template_covercorner" : "Couverture en coin",
			"Template_alignbottom" : "Aligné en bas",
			"Template_aligncenter" : "Aligné au centre",
			"Template_puzzle" : "Puzzle",
			"Template_random" : "Aléatoire",
			"Template_vertical" : "Vertical",
			"Template_vertical2" : "Vertical 2",
			"Template_slideshow1" : "Diaporama 1",
			"Template_slideshow2" : "Diaporama 2",
			"Template_slideshow4" : "Diaporama 4",
			"Template_slideshowleft" : "Diaporama à gauche",
			"Template_slideshowright" : "Diaporama à droite",
			"Template_halfscreenslideshow" : "Diaporama demi-écran",
			"Template_halfscreenslideshowright" : "Diaporama demi-écran 2",
			"Template_slideshowfullscreen" : "Plein écran",
			"Template_parallax" : "Parallax",
			"Template_circles" : "Cercles",
			"Template_zigzag" : "Zig Zag",
			"Template_boxes" : "Boîtes",
			"Template_boxes2" : "Grille 1",
			"Grid" : "Grille",
			"Template_skewed" : "asymétrie",
			"Template_quotas1" : "Citations 1",
			"Template_sidetoside" : "Côte à côte",
			"Template_servicesgrid" : "Grille 2",
			"Template_dynamicgrid" : "Grille dynamique",
			"Template_twoone" : "Deux & un",
			"Template_horizontal" : "Horizontal",
			"Template_horizontal2" : "Horizontal 2",
			"Template_horizontal3" : "Horizontal 3",
			"Template_submenu1" : "Centré 1",
			"Template_submenucentered2" : "Centré 2",
			"Template_submenubig" : "Grand sous-menu",
			"Template_menuhalfscreen" : "Menu demi-écran",
			"Template_submenu4" : "Sous-menu 4",
			"Template_footercolumns" : "Colonnes",
			"Template_footercolumns2" : "Colonnes 2",
			"Template_twosides1" : "Deux côtés 1",
			"Template_social1" : "Social 1",
			"Template_email1" : "Email 1",
			"Template_actionbutton1" : "Bouton 1",
			"Template_actioncolumns" : "Colonnes 1",
			"Template_actioncover" : "Couverture d'action",
			"Template_actionsignup" : "Inscription 1",
			"Template_onequota1" : "Une citation 1",
			"Template_footer0" : "Pied de page simple",
			"Template_footer1" : "Pied de page 1",
			"Template_footer2" : "Pied de page 2",
			"Template_footer3" : "Pied de page 2",
			"Template_threeone" : "Trois & un",
			"Template_twotextcolumns" : "Deux colonnes",
			"Template_twotextcolumns3" : "Deux colonnes 3",
			"MenuTemplate_centered1" : "Centré 1",
			"MenuTemplate_centered2" : "Centré 2",
			"MenuTemplate_centered3" : "Centré 3",
			"MenuTemplate_left3" : "Gauche 3",
			"MenuTemplate_left1" : "Gauche 1",
			"MenuTemplate_left2" : "Gauche 2",
			"MenuTemplate_hidden1" : "Masqué 1",
			"MenuTemplate_hidden2" : "Masqué 2",
			"MenuTemplate_hidden3" : "Masqué 3",
			"MenuTemplate_hidden4" : "Masqué 4",
			"MenuTemplate_hidden5" : "Masqué 5",
			"MenuTemplate_hidden6" : "Masqué 6",
			"MenuTemplate_hidden7" : "Masqué 7",
			"MenuTemplate_minimal" : "Minimal",
			"MenuTemplate_verticallogoright" : "Logo à droite",
			"MenuTemplate_bordertop1" : "Bordure en haut 1",
			"MenuTemplate_bordertop2" : "Bordure en haut 2",
			"MenuTemplate_bordertop3" : "Bordure en haut 3",
			"ExampleText_gallery" : "Dans cette galerie, vous pouvez voir une sélection de mes travaux. J'espère que vous apprécierez.",
			"ExampleText_products" : "Consulter mes derniers produits ci-dessous. Pour voir tous les produits, visitez ma boutique.",
			"ExampleText_team" : "Rencontrez notre équipe de créatifs heureux. Nous aimons ce que nous faisons et aimerions travailler avec vous.",
			"ExampleText_service" : "Vous trouverez ci-dessous une liste des services que je propose. Contactez-moi si vous voulez en savoir plus.",
			"ExampleText_link" : "Ci-dessous, vous pouvez voir des liens vers mes galeries. Cliquez sur une image pour voir la galerie.",
			"ExampleText_logos" : "Nous avons travaillé avec certaines des entreprises les plus intéressantes au monde.",
			"ExampleText_testimonials" : "J'ai travaillé avec une variété de grandes entreprises. Vous pouvez lire ici certains de leurs avis.",
			"ExampleText_storeText" : "Bienvenue dans notre boutique Tous les articles de cette page sont disponibles à la vente. Cliquez sur un élément pour voir les détails.",
			"GenericText_cookie" : "Nous utilisons des cookies et des technologies similaires pour améliorer votre expérience sur ce site Internet. Pour continuer à naviguer sur ce site, vous devez accepter.",
			"GenericText_manualPaymentInf" : "Une fois la commande complétée, vous recevrez un email avec les instructions de paiement.",
			"YourComment" : "Votre commentaire",
			"YourMessage" : "Votre message",
			"YourName" : "Votre nom",
			"YourEmail" : "Votre e-mail",
			"YourAddress" : "Votre adresse",
			"YourZip" : "Votre code postal",
			"YourCity" : "Votre ville",
			"YourCountry" : "Votre pays",
			"YourState" : "Votre région",
			"WillNotBePublic" : "Ne sera pas public",
			"Submit" : "Envoyer",
			"AreYouSure" : "Êtes-vous sûr?",
			"NoFieldsCanBeEmpty" : "Tous les champs doivent être renseignés",
			"Welcome" : "Bienvenue",
			"Login" : "Connexion",
			"SelectImages" : "Sélectionner des images",
			"SelectImagesForClientGallery" : "Sélectionnez des images avec l'icône plus et soumettez votre sélection lorsque vous avez terminé.",
			"OnlySelected" : "Sélectionnées seulement",
			"OnlyCommented" : "Commentées seulement",
			"ImagesSelected" : "Images sélectionnées",
			"Home" : "Accueil",
			"Labels" : "Étiquettes",
			"New" : "Nouveau",
			"OnSale" : "Promo",
			"Popular" : "Populaire",
			"LastChance" : "Dernière chance",
			"SortBy" : "Trier par",
			"Latest" : "Dernier",
			"AddToCart" : "Ajouter au panier",
			"PleaseSelectOneVariant" : "Sélectionnez une des variantes.",
			"ItemAddedToCart" : "Merci! Cet article a été ajouté au panier.",
			"CheckoutThis" : "Jetez un œil à ce :",
			"ChooseAVariant" : "Sélectionnez une variante",
			"AreYouSureRemoveFromCart" : "Êtes-vous sûr de vouloir supprimer ce produit du panier?",
			"ShippingAddress" : "Adresse de livraison",
			"ShipToThisAddress" : "Expédier à cette adresse",
			"ShipToAnotherAddress" : "Expédier à une autre adresse.",
			"Zip" : "Code postal",
			"City" : "Ville",
			"NeedToAcceptTerms" : "Vous devez accepter les conditions générales de vente.",
			"DiscountCodeWasNotValid" : "Désolé! Le code de réduction n'était pas valide",
			"DiscountApplied" : "Nous avons appliqué votre réduction!",
			"Subtotal" : "Sous-total",
			"YourCart" : "Votre panier",
			"ContextMenuHeader_StoreCartRow" : "Votre panier",
			"ReviewYourOrder" : "Vérifiez votre commande",
			"YourInfo" : "Vos coordonnées",
			"Check" : "Vérifier",
			"ProceedToCheckout" : "Poursuivre la commande",
			"ExcludedFromTax" : "TVA excluse",
			"TaxIsIncluded" : "TVA incluse",
			"TaxIsIncludedExp" : "Vous recevrez un reçu détaillant la TVA",
			"ShippingCostAddedLater" : "Les frais d'expédition seront ajoutés après confirmation de la commande.",
			"Total" : "Total",
			"IAcceptTerms" : "J'accepte les conditions générales et la politique de confidentialité",
			"Confirm" : "Confirmer",
			"CompleteOrder" : "Finaliser la commande",
			"CheckoutNotAvailable" : "Le paiement n'est pas disponible pour",
			"ButThereIsHope" : "Mais il y a de l'espoir, veuillez cliquer ci-dessous et je traiterai votre commande manuellement.",
			"DoManualCheckout" : "Faire le paiement manuellement",
			"HowWouldYouLikeToPay" : "Comment souhaitez-vous payer?",
			"WithPayPal" : "Avec PayPal.",
			"WithCard" : "Payer avec une carte de bancaire",
			"ThankYouForMakingOrder" : "Merci d'avoir passé commande! Je vous contacterai sous peu.",
			"ThankYouForMakingManualOrder" : "Merci! Je vous contacterai sous peu pour traiter votre commande.",
			"TermsAndPrivacy" : "Conditions et politique de confidentialité",
			"AddYourContentToGetStarted" : "Ajoutez votre contenu pour commencer",
			"Click" : "Cliquez",
			"NotVisibleInAllTemplates" : "Non visible dans tous les modèles",
			"VisibleInLightbox" : "Visible dans la visionneuse",
			"ReverseOrderOfImages" : "Inverser l'ordre (des images et du texte)",
			"AnErrorOccurred" : "Une erreur est survenue. Si vous avez besoin d'aide, contactez-nous via le Chat dans le coin inférieur droit.",
			"CantUseDiscountIfDiscount" : "Désolé! Vous ne pouvez pas utiliser le code de réduction car votre compte a déjà obtenu une remise.",
			"ReloadAdminVideoExp" : "Vous devez actualiser votre navigateur afin que la modification de la vidéo soit effective.",
			"Template_music1" : "Musique 1",
			"Template_music2" : "Musique 2",
			"Template_music3" : "Musique 3",
			"Preview" : "Aperçu",
			"MobilePreview" : "Aperçu mobile",
			"LinkToAPdf" : "Lien vers un PDF",
			"UploadPdf" : "Télécharger un PDF",
			"APdf" : "Un PDF",
			"SeoKeywordsExp" : "Mots clés utilisés par certains moteurs de recherche pour indexer votre site. (Non utilisés par Google. Normalement considérés comme sans valeur.)",
			"TheFileWasDeleted" : "Le fichier a été supprimé",
			"NameOnCard" : "Nom sur la carte",
			"CardNumber" : "Numéro de carte",
			"ExpiryDate" : "Date d'expiration",
			"Cvc" : "Code de sécurité (CVC)",
			"VatNrPaymentExp" : "Facultatif et uniquement pour les entreprises de l'UE avec un numéro de TVA valide.",
			"SelectCountry" : "Sélectionnez un pays",
			"CompletePayment" : "Effectuer le règlement",
			"SecuredByStripe" : "Sécurisé par Stripe",
			"LinkReload" : "Le lien est correctement mis à jour, mais lorsque vous modifiez le type du lien, vous devez actualiser votre navigateur avant de le tester.",
			"SecuredByStripeExp" : "Le paiement est géré par Stripe. Portfoliobox ne conserve jamais les détails de votre carte bancaire.",
			"StipeIsRevoked" : "Vous avez réussi à supprimer Stripe.",
			"StripeConnected" : "Vous avez réussi à vous connecter à Stripe.",
			"ConnectStripe" : "Connexion à Stripe",
			"ConnectStripeExp" : "Stripe est utilisé pour les paiements par carte bancaire. Vous devez créer un compte sur Stripe puis cliquer sur ce bouton pour utiliser Stripe dans votre boutique.",
			"RemoveStripe" : "Supprimer Stripe",
			"NeedToFillInTheNameOnCard" : "Vous devez renseigner le nom de la carte",
			"PleaseSelectYourCountry" : "Veuillez sélectionner votre pays",
			"PleaseTryAgain" : "Une erreur est survenue, veuillez réessayer.",
			"ThereWasAProblemWithThePayment" : "Une erreur s'est produite lors du traitement de votre paiement, veuillez contacter le service client.",
			"Active" : "Actif",
			"MobileStyles" : "Style dans Mobile",
			"Order" : "Commande",
			"Id" : "Id",
			"NrOfProducts" : "Nombre de produits",
			"Customer" : "Client",
			"Discount" : "Réduction",
			"Quantity" : "Quantité",
			"ManuelPaymentDoneExp" : "Cliquez sur ce bouton si vous avez reçu un paiement manuel via Paypal.",
			"AreYouSureToComplete" : "Êtes-vous sur de vouloir terminer cette commande?",
			"TheOrderIsCompleted" : "La commande est terminée.",
			"ThereWasAProblemWithCardChange" : "Une erreur est survenue lors du changement de carte, veuillez contacter l'assistance client.",
			"ActivateAdvancedStyles" : "Activer les Styles Avancés",
			"AdvancedStylesUpgradeMessage" : "Avec les Styles Avancés, vous pouvez modifier les tailles, les marges et les animations. Vous pouvez également ajouter de nouveaux éléments au modèle et les réorganiser.",
			"ResetMenu" : "Réinitialiser le menu",
			"AreYouSureResetTheMenu" : "Êtes-vous sur de vouloir réinitialiser le menu? Toutes les modifications seront perdues.",
			"YourConnectionWasLost" : "IMPORTANT! Votre connexion internet a été interrompue. Aucune modification ne sera enregistrée. Assurez-vous que d'être connecté à Internet avant de continuer.",
			"ChooseAFont" : "Choisir la police",
			"ChooseBackground" : "Choisir l'arrière plan",
			"White" : "Blanc",
			"LightGrey" : "Gris clair",
			"DarkGrey" : "Gris foncé",
			"Black" : "Noir",
			"ChooseATheme" : "Choisir  un thème",
			"HowManyGalleries" : "Combien de galeries voulez-vous ajouter à votre site ?",
			"One" : "Une",
			"Several" : "Plusieurs",
			"Nature" : "Nature",
			"Portraits" : "Portraits",
			"Landscapes" : "Paysages",
			"Street" : "Photographie de rue",
			"Portfolio" : "Portfolio",
			"About" : "À Propos",
			"VatNrMsg": "Les deux premiers caractères doivent être le code de votre pays",
			"DoYouWantToStartWithSampleContent" : "Voulez-vous commencer avec un exemple de contenu?",
			"StartEmpty" : "Démarrer vide",
			"StartWithSamplePages" : "Commencez avec des exemples de pages",
			"ChooseSampleContent" : "Choisissez un exemple de contenu",
			"StartWithSampleImages" : "Commencez avec des exemples d'images",
			"UploadImagesNow" : "Téléchargez vos images maintenant",
			"CantChangeThisTemplate" : "Ce modèle ne peut être modifié. Veuillez créer une nouvelle page.",
			"BackgroundImageScrolling" : "Défilement de l'image d'arrière-plan",
			"BackgroundImageRepeat" : "Répétition de l'image d'arrière-plan",
			"AreYouSureToUpgradeLightPro" : "Voulez-vous vraiment passer de Light à PRO?",
			"StartWithSampleLinks" : "Commencer avec des Liens échantillons",
			"AddLinks" : "Ajouter des liens",
			"ChoosePagesToLinkTo" : "Choisir les pages vers lesquelles créer un lien",
			"Choose" : "OK",
			"AddToLinkPage" : "Ajouter la galerie à l'une de vos pages Liens",
			"DontAdd" : "Ne pas ajouter",
			"Restore" : "Restaurer",
			"CollectGalleriesOnALinkPage" : "Comment collecter des galeries sur une page de liens",
			"DontReloadUntilAfterSave" : "NB ! N'actualisez pas le navigateur avant d'avoir enregistré le lien.",
			"Domains" : "Domaines",
			"YouAlreadyHaveAnActiveSubscription": "Vous avez un abonnement actif dans l'ancienne version de Portfoliobox. Vous devez le déplacer ici.",
			"YouAlreadyHaveAnActiveDomain": "Vous avez un domaine dans l'ancienne version de Portfoliobox. Vous devez le déplacer ici.",
			"WillCloseYourOldAccount": "Cette action mettra fin à votre ancien compte.",
			"GetMySubscription": "Obtenir mon abonnement",
			"GetMyDomain": "Obtenir mon domaine",
			"MoveSubscription": "Déplacer votre abonnement",
			"YourOldSubscriptionWasNotFound": "Votre ancien compte est introuvable. Veuillez mettre à niveau / publier à nouveau ou contacter le support.",
			"YouNeedToMoveSubToActivateDomain": "Vous devez déplacer votre abonnement avant de pouvoir activer votre domaine. Cliquez sur le bouton ci-dessous pour déplacer l'abonnement.",
			"EnterYourCardToMove": "Entrez les détails de votre carte pour déplacer l'abonnement.",
			"NoMoneyWillBeChargedNow": "Aucun argent ne sera débité maintenant.",
			"OnlyPostWithImagesWillBeDisplayed" : "Seuls les messages contenant des images seront affichés.",
			"SoldOut": "Epuisé",
			"SoldOutMessage": "Ce produit est en rupture de stock.",
			"HowToMobileEdit": "La meilleure façon de prévisualiser la version mobile est de réduire la taille de votre navigateur Web (largeur inférieure à 1 000 pixels). Pour modifier en mode mobile - Rechargez le navigateur, puis cliquez et maintenez n'importe quel élément à modifier.",
			"FirstYearFree": "Première année gratuite",
			"GoogleCalendar": "Google Agenda",
			"ContextMenuHeader_GoogleCalendar": "Modifier le calendrier",
			"EditCalendar": "Modifier le calendrier",
			"GoogleCalendarId": "ID Google Agenda",
			"GoogleCalendarIdExp": "L'ID de votre calendrier",
			"Now" : "Maintenant",
			"FirstMonthFree": "Premier mois gratuit",
			"ExportToCVS": "Exporter les messages vers CSV",
			"RemoveStyles": "Supprimer les styles",
			"AreYouSureThatYouWantToRemoveStyles": "Êtes-vous sûr de vouloir supprimer tous les styles?",
			"EmailToCustomerAfterCheckout": "Message électronique au client après la commande",
			"EmailToCustomerAfterCheckoutAdd": "Ajouter un message générique",
			"GenericText_checkoutEmail": "Merci pour votre commande. Je traite votre commande le plus rapidement possible.",
			"ImportFromAdobeLightroom": "Importer depuis Adobe Lightroom",
			"EmbedHeader": "Embed",
			"EditKuula": "Modifier Kuula",
			"EditMap": "Modifier la carte",
			"ContextMenuHeader_Kuula": "Modifier Kuula",
			"ContextMenuHeader_GoogleMap": "Modifier la carte",
			"KuulaIdExp": "L'identité de votre image Kuula 360.",
			"GoogleMapIframe": "Google Map iFrame",
			"GoogleMapIframeExp": "L'ensemble de l'iFrame de Google Map que vous souhaitez intégrer",
			"TheContentCouldNotBeEmbedded": "Le contenu n'a pas pu être intégré",
			"YourPhone" : "Votre numéro de téléphone",
			"CopyToPage": "Copier sur la page",
			"LoadMore" : "Charger plus",
			"Print": "Imprimer",
			"ContextMenuHeader_SpeakerDeck" : "Modifier la platine de haut-parleurs",
			"EditSpeakerDeck" : "Modifier l'URL du Speaker Deck",
			"SpeakerDeckURL" : "URL de votre Deck",
			"SavingInProgress" : "Veuillez patienter, l'enregistrement du contenu est en cours",
			"EditSlides" : "Modifier les diapositives",
			"ContextMenuHeader_EditSlides" : "Modifier les diapositives",
			"GoogleSlidesIframe" : "Google Slides iFrame",
			"GoogleSlidesIframeExp" : "L'iFrame entier des Google Slides que vous souhaitez intégrer",
			"SpeakerDeckExp": "Le lien vers votre SpeakerDeck",
			"HideBreadCrumbs": "Masquer la navigation",
			"HideBreadCrumbsExp": "Masquer la navigation sur la page produit",
			"ToggleBreadCrumbsConf": "Êtes-vous sûr de vouloir afficher / masquer la navigation?",
			"ToggleSearchRow": "Êtes-vous sûr de vouloir afficher / masquer la ligne de recherche?",
			"SearchRowStyle": "Recherche et catégories - Style",
			"SearchRowStyleExp": "Style de la ligne de recherche sur la page Store. Vous pouvez également la masquer.",
			"SetTheStoreAsYourStartPage": "Définir le magasin comme page de démarrage",
			"SetTheBlogAsYourStartPage": "Définir le blog comme votre page de démarrage",
			"ThisWasTheStartPage": "Comme il s'agissait de votre page de démarrage, vous devez maintenant définir une autre page comme page de démarrage de votre site.",
			"ContextMenuHeader_PDF" : "Modifier l'URL du PDF",
			"EditEmbedPDF" : "Modifier l'URL du PDF",
			"EmbedPDF" : "URL du fichier PDF",
			"EmbedPDFExpHttps" : "L'URL doit commencer par https:// et l'extension doit être .pdf",
			"ShowHideToolbar" : "Afficher/masquer la barre d'outils de la visionneuse PDF",
			"NotForLightbox" : "Pas pour Lightbox",
			"LinksDontWorkInAdmin" : "Les liens ajoutés au texte ne fonctionnent pas dans le panneau d'administration. Ils travailleront sur votre site Web en direct.",
			"FooterOnPage": "Pied de page",
			"FooterOnPageExp": "Un simple pied de page pour vos pages Store et Product. Si vous souhaitez ajouter des sections et modifier le style - Ajoutez une section Store à une page standard.",
			"FooterOnBlogExp": "Un pied de page simple pour vos pages de blog et de publication. Si vous souhaitez ajouter des sections et modifier le style - Ajoutez une section de blog à une page normale.",
			"EditFooter": "Modifier le pied de page",
			"ContextMenuHeader_StoreFooter": "Modifier le pied de page",
			"ContextMenuHeader_BlogFooter": "Modifier le pied de page",
			"UnPublishStoreConf" : "Voulez-vous vraiment annuler la publication de votre boutique?",
			"LightDontHaveDomain": "Le compte Light n'inclut pas de nom de domaine premium - par exemple: www.yourname.com.",
			"LightDontHaveDomain2": "Vous ne pouvez pas connecter votre propre domaine premium au compte Light.",
			"LightDontHaveDomain3": "Vous obtiendrez un domaine Portfoliobox - par exemple: votrenom.portfoliobox.net.",
			"DoYouWantToContinue": "Voulez-vous continuer?",
			"Continue": "Continuer",
			"SectionProd": "Produits",
			"SectionNews": "Articles de blog",
			"NotResponsibleForText": "Les portfoliobox ne sont en aucun cas",
			"YourLibraries": "Vos bibliothèques",
			"YourProducts": "Vos produits",
			"YourImages": "Vos images",
			"BlogPosts": "Articles de blog",
			"YourBlogPosts": "Vos articles de blog",
			"EditBlogTeaser": "Modifier le blog",
			"EditProductTeaser": "Modifier les produits",
			"ContextMenuHeader_SectionProd": "Modifier les produits",
			"ContextMenuHeader_SectionNews": "Modifier le blog",
			"TheProductsWillBeSelectedBasedOnThis": "Les produits seront sélectionnés dans votre bibliothèque en fonction de cette option",
			"AllProducts": "Tous les produits",
			"AllPosts": "Tous les articles du blog",
			"AddNewProductsToYourLibrary": "Ajouter de nouveaux produits à votre bibliothèque",
			"AddNewPostsToYourLibrary": "Ajouter de nouveaux articles à votre bibliothèque",
			"StoreTeaser": "Produits",
			"BlogTeaser": "Blog",
			"ThePostWillBeSelected": "Le message sera sélectionné dans votre bibliothèque de blogs en fonction de cette option",
			"ExampleText_blog": "Bienvenue sur mon blog. Ici, je publierai des actualités et des mises à jour.",
			"Template_fullposts": "Articles complets",
			"SortFilter": "Filtre",
			"SearchSortAndCategories": "Recherche, catégories et tri",
			"CategoryCloud": "Cloud",
			"PostWithCategory": "Articles de blog avec une certaine catégorie",
			"BlogCategories": "Catégories de blog",
			"FromCategoryDesc": "Seuls les éléments de cette catégorie seront affichés.",
			"SortFilterDesc": "Laissez vos visiteurs rechercher et filtrer la liste.",
			"SearchAndCategories": "Recherche et catégories",
			"AddNewCategoryStore": "Ajouter de nouvelles catégories dans Paramètres> Boutique",
			"AddNewCategoryBlog": "Ajouter de nouvelles catégories dans Paramètres> Blog",
			"LinkToProduct" : "Un de vos produits",
			"BuyMeACoffee" : "Buy Me a Coffee",
			"BuyMeACoffeeID": "L'ID de votre bouton Buy Me a Coffee.",
			"ContextMenuHeader_BuyMeACoffee": "Modifier Buy Me A Coffee",
			"ContextMenuHeader_PayPalDonate": "Modifier PayPal Donate",
			"ContextMenuHeader_ShapeSpark": "Modifier ShapePark",
			"ContextMenuHeader_SketchFab": "Modifier SketchFab",
			"PayPalDonate": "PayPal Faire un don",
			"PayPalDonateID": "L'ID de votre bouton Donate PayPal.",
			"ShapeSpark": "ShapePark",
			"ShapeSparkScene": "Le nom de votre scène dans ShapePark.",
			"ShapeSparkUser": "Votre nom d'utilisateur dans ShapePark.",
			"SketchFab": "SketchFab",
			"SketchFabID": "ID de votre iframe intégré SketchFab.",
			"TermsDisclaimer": "Ce texte est fourni tel quel et tel que disponible. Vous acceptez que votre utilisation de ce texte se fera à vos risques et périls.",
			"Variant" : "Une variante",
			"DefaultStylesMobile": "Styles mobiles",
			"DefaultStylesMobile_Gallery": "Style de la galerie",
			"DefaultStylesMobile_Menu": "Style de menu",
			"ItemsPerRow": "Articles par ligne",
			"ItemsPerRow_One": "Un",
			"ItemsPerRow_Two": "Deux",
			"MobileMenuPosition": "Position d'icône de menu",
			"AboveLogo": "Logo ci-dessus",
			"BelowLogo": "Logo ci-dessous",
			"BottomOfPage": "Bas de la page",
			"Default": "Par défaut",
			"HiddenMenuStyle": "Style de menu masqué",
			"LeftOfLogo": "Gauche du Logo",
			"Position": "Position",
			"RightOfLogo": "Droit du logo",
			"FixateRightClickToEdit": "CLIC DROIT: Le menu couvre également les boutons d'édition - vous devez donc faire un clic droit sur l'élément à modifier.",
			"FixateWarning": "Si vous fixez le menu en haut de la page, il couvrira la section ci-dessous. Si vous voulez que le contenu soit visible, vous devez augmenter le pagayage de la section. Remarque - vous devrez également ajuster le padding-top pour mobile.",
			"Cancel": "Annuler",
			"CancelSubMessText": "Cette action annulera l'abonnement à la fin de la période en cours et votre compte sera déclassé en version d'essai.",
			"CancelSubMessWarning": "AVERTISSEMENT! Si vous avez un nom de domaine via Portfoliobox, ce nom de domaine sera perdu.",
			"FailedCancelSubscription": "Impossible d'annuler l'abonnement, veuillez contacter le support technique.",
			"PleaseLetUsKnowWhyCancel": "S'il vous plaît laissez-nous savoir pourquoi vous choisissez d'annuler l'abonnement.",
			"TheSubscriptionWillBeCanceled": "L'abonnement sera annulé à",
			"YourSubscriptionWillBeCanceled": "Votre abonnement sera annulé",
			"YouCantChooseLight": "Vous ne pouvez pas mettre à niveau vers ce package si votre compte a déjà été rétrogradé.",
			"JustForStudents": "Remise pour les étudiants",
			"StudentsGetItFree": "En tant qu'étudiant, vous bénéficiez d'une réduction de 100% sur notre compte PRO Annuel.",
			"StudentsGetItFree2": "La réduction sera ajoutée à la caisse.",
			"TheDiscountWasNotApplied": "La réduction n'a pas été appliquée.",
			"ThisCodeCanOnlyBeUsedForAnotherPackage": "Ce Code ne peut être utilisé que pour un autre Paquet:",
			"CopyToPageOrProduct": "Copier vers la page ou le produit",
			"CopyToProduct": "Copier vers le produit",
			"DuplicateSection": "Section Dupliquer",
			"DiscountAmount": "Montant",
			"DiscountCheapestFree": "Article le moins cher gratuit",
			"DiscountFixedAmount": "Montant fixe",
			"DiscountFreeShipping": "Livraison gratuite",
			"DiscountLimit": "Limite",
			"DiscountNumberOfItems": "Nombre d'articles",
			"DiscountOrderAbove": "Commandes supérieures à la limite",
			"DiscountPercentage": "Pourcentage de la valeur de la commande",
			"DiscountRule": "Règle de remise",
			"DiscountType": "Type de remise",
			
			"CalendlyIdExp": "Inserisci il tuo Calendly Id",
			"ContextMenuHeader_Calendly": "Modifica Calendly",
			"ContextMenuHeader_Elfsight": "Modifica Elfsight",
			"ContextMenuHeader_PickTime": "Modifica PickTime",
			"ContextMenuHeader_Resurva": "Modifica Resurva",
			"ContextMenuHeader_Typeform": "Modifica Typeform",
			"CopyVariantsToOtherProduct": "Copia queste varianti in un altro prodotto",
			"EditCalendly": "Il tuo Calendly ID",
			"EditTypeform": "Modifica Typeform",
			"ElfsightHint": "Inserisci il tuo ID Elfsignt",
			"ElfsightID": "Il tuo ID Elfsight.",
			"GoogleTagManagerDone": "L'ID Google Tag Manager viene salvato e Tag Manager viene aggiunto al tuo sito live. (Non può essere ispezionato nel pannello di amministrazione).",
			"GoogleTagManagerTrackingId": "ID Google Tag Manager",
			"GoogleTagManagerTrackingIdExp": "Avvia Tag Manager per il tuo sito web. Inserisci qui il numero di spedizione.",
			"LinkToThisPhone": "Link a questo telefono",
			"NeedToClickSaveEmail": "Il campo email è vuoto. Non dimenticare di fare clic sul pulsante Salva e-mail.",
			"OpenPayPal": "Apri PayPal",
			"PhoneLink": "Telefono",
			"PickTime": "Ora di prelievo",
			"PickTimeID": "L'ID del pulsante PickTime.",
			"PickTimeText": "Suggerimento sul pulsante",
			"Published": "Pubblicato",
			"Resurva": "Resurva",
			"ResurvaIframe": "iFrame Resurva",
			"ResurvaIframeExp": "L'intero iFrame di Resurva che vuoi incorporare",
			"SecuredbyPayPal": "Garantiito da PayPal",
			"TheVariantsWereCopied": "Le varianti sono state copiate con successo.",
			"TranslationNotice": "Queste parole vengono visualizzate sul tuo sito. Puoi tradurli qui.",
			"TypeformIdExp": "Inserisci il tuo ID Typeform",
			"UnPublished": "Inedito",
			"AllFieldsAreEmpty": "Tous les champs sont vides",
			"MakeMandatory": "obligatoire",
			"MandatoryFieldsAreEmpty": "Certains champs obligatoires sont vides.",
			"TwitterUsername": "Nom d'utilisateur Twitter",
			"TwitterUsernameExp": "Utilisé pour générer une carte Twitter lorsque votre site Web est partagé sur Twitter.",
			"AddContent": "Ajouter du contenu",
			"ChooseContent": "Choisissez le type de contenu",
			"ContactForm": "Contact De",
			"ContextMenuHeader_Header2": "Modifier l'en-tête 2",
			"ContextMenuHeader_Header3": "Modifier l'en-tête 3",
			"DefaultStyles_Header2": "En-tête 2",
			"DefaultStyles_Header3": "En-tête 3",
			"ExperienceList": "Liste des expériences",
			"FourColumns": "Quatre colonnes",
			"ImageLink": "Lien vers l'image",
			"Media": "Média",
			"Paragraph": "Le paragraphe",
			"ShortText": "Texte court",
			"SignupForm": "Inscription à partir de",
			"Structure": "Structure",
			"ThreeColumns": "Trois colonnes",
			"TwoColumns": "Deux colonnes",
			"Captions": "Légendes",
			"DefaultStylesExp": "Contexte du site Web et police générale",
			"GeneralButtonsExp": "Styles pour les boutons sur votre site Web.",
			"GeneralCaptionsExp": "Style général des légendes de vos galeries",
			"GeneralHeadersExp": "Styles généraux des en-têtes. Ces paramètres ne remplacent pas les styles que vous avez définis sur des en-têtes individuels.",
			"GeneralLinksExp": "Styles pour les liens sur votre site Web.",
			"GeneralParagraphsExp": "Styles généraux des paragraphes. Ces paramètres ne remplacent pas les styles que vous avez définis dans vos pages.",
			"GeneralSubtitlesExp": "Style général des sous-titres de légende dans vos galeries",
			"MobileButtons": "Boutons mobiles",
			"MobileButtonsExp": "Style des boutons sur le mobile.",
			"MobileCaptionSubtitles": "Sous-titres mobiles",
			"MobileCaptionSubtitlesExp": "Style pour les sous-titres de légende sur mobile.",
			"MobileCaptions": "Légendes mobiles",
			"MobileCaptionsExp": "Style des légendes sur le mobile.",
			"MobileHeaders": "En-têtes mobiles",
			"MobileHeadersExp": "Style pour les en-têtes sur mobile. Les en-têtes héritent des styles de bureau. Vous n'avez donc qu'à ajuster des propriétés spécifiques.",
			"MobileMenu": "Menu mobile",
			"MobileMenuExp": "Modifier le style de votre menu mobile",
			"MobileParagraphs": "Paragraphes",
			"MobileParagraphsExp": "Style des paragraphes sur le mobile. Le paragraphe hérite des styles de bureau, il vous suffit donc d'ajuster des propriétés spécifiques.",
			"OnHover": "En vol stationnaire",
			"OverallStyles": "Styles globaux",
			"ResetStyles": "Reset Styles",
			"Styles": "Styles",
			"GoToGlobal": "Ouvrir plutôt les styles globaux",
			"IndividualOrGlobalStyles": "Styles individuels ou globaux",
			"IndividualOrGlobalStylesExp": "Ces styles s'appliquent uniquement à cet élément. Si vous souhaitez avoir le même style sur tous les éléments de ce type, utilisez les styles généraux.",
			"stab_animation": "Animations",
			"stab_animation_exp": "Animations de l'élément",
			"stab_bar": "Couleurs des barres",
			"stab_bar_exp": "Modifier les couleurs des barres",
			"stab_bgborder": "Contexte et bordures",
			"stab_bgborder_exp": "Style de l'arrière-plan et des bordures",
			"stab_font": "Police",
			"stab_font_exp": "Couleur et police de l'élément",
			"stab_icons": "Icônes",
			"stab_icons_exp": "Style et comportement des icônes",
			"stab_items": "Styles d'image",
			"stab_items_exp": "Tailles et styles des articles",
			"stab_lightbox": "Lightbox",
			"stab_lightbox_exp": "Paramètres de la visionneuse",
			"stab_links": "Liens",
			"stab_links_exp": "Modifier le style des liens",
			"stab_margins": "Marges",
			"stab_margins_exp": "Modifier la marge et la marge intérieure",
			"stab_mobile": "Styles mobiles",
			"stab_mobile_exp": "Remplacements de style pour mobile",
			"stab_size": "Taille",
			"stab_size_exp": "Modifier la taille et la position",
			"stab_titles": "Titres",
			"stab_titles_exp": "Styles des légendes",
			"stab_video": "Vidéo",
			"stab_video_exp": "Paramètres de la vidéo",
			"IncludedInLightPlan": "Inclus dans le compte Light",
			"OpenStyleEditor": "Éditeur de style ouvert",
			"ReorderElements": "Réorganiser les éléments",
			"MobileGalleryExp": "Style pour les galeries sur mobile",
			"AddGenericInstructions": "Ajouter des instructions génériques",
			"AddGenericMessage": "Ajouter un message générique",
			"Checkout": "Checkout",
			"ConfirmOrder": "Confirmer la",
			"EnableInvoice": "Activer la facture",
			"EnableInvoiceExp": "Votre client recevra une facture avec vos instructions de paiement.",
			"EnablePaypalCheckoutExp2": "Acceptez les paiements, y compris les cartes de crédit, via PayPal. Créez un compte PayPal et ajoutez l'adresse e-mail du compte ici.",
			"GenericText_invoiceMessage": "Veuillez virer le montant sur mon compte: +46000000. Nous traiterons la commande une fois que nous aurons reçu l'argent.",
			"GenericText_paymentInstructions": "Compte bancaire: 444 555 666. Swift: SE8855. Veuillez utiliser le numéro de commande comme numéro de référence.",
			"Invoice": "Facture",
			"InvoiceInstructions": "Vos instructions de paiement",
			"InvoiceInstructionsExp": "Vos instructions de paiement. Sera visible sur la facture.",
			"InvoiceMessage": "Message après le paiement",
			"InvoiceMessageExp": "Sera visible à l'écran juste après que la commande a été passée.",
			"InvoiceTimeframe": "Délai",
			"InvoiceTimeframeExp": "Nombre de jours avant que le paiement ne soit effectué.",
			"OrderConfirmation": "confirmation de la commande",
			"PaidWith": "Payé avec:",
			"PayNow": "Payez maintenant",
			"PayWithCard": "Payez avec une carte",
			"PayWithPayPal": "Payez avec PayPal",
			"PayWithPayPalExp": "Ouvrez PayPal pour finaliser la commande.",
			"PayWithin": "Payez dans les délais:",
			"Receipt": "Reçu",
			"ThankYouForYourOrder": "Merci de votre commande",
			"WithInvoice": "Avec facture",
			"PayButtonNotSupport": "Votre appareil n'est pas compatible",
			"PayWithPayButton": "Payer avec Google/Apple/Navigateur",
			"ConfigureCheckout": "Masquer les champs dans la caisse",
			"ContinueShopping": "Continuer vos achats",
			"GoToCheckout": "Aller à la caisse",
			"SubscribeToNews": "Abonnez-vous à News",
			"ClearHeaders": "Supprimer les en-têtes",
			"ContactForm2": "Formulaire de contact",
			"ContextMenuHeader_LinkImage": "Modifier l'image",
			"SignupForm2": "Formulaire d'inscription",
			"BackgroundPositionX": "Position d'arrière-plan X",
			"BackgroundPositionY": "Position d'arrière-plan Y",
			"Direction": "Direction",
			"Row": "Row",
			"Allow": "Autoriser",
			"AllowNecessary": "Autoriser nécessaire",
			"LeaveWebsite": "Quitter le site"
		}
	}
};